#if !canImport(ObjectiveC)
import XCTest

extension ImGuiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImGuiTests = [
        ("testCreateContext", testCreateContext),
        ("testGetIO", testGetIO),
        ("testVersion", testVersion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ImGuiTests.__allTests__ImGuiTests),
    ]
}
#endif
