#if !canImport(ObjectiveC)
import XCTest

extension ImGUITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImGUITests = [
        ("testHelloImGUI", testHelloImGUI)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ImGUITests.__allTests__ImGUITests)
    ]
}
#endif
