#ifndef CIMGUI_UMBRELLA_HEADER
#define CIMGUI_UMBRELLA_HEADER

#define CIMGUI_DEFINE_ENUMS_AND_STRUCTS
#define CIMGUI_NO_EXPORT
#define IMGUI_DISABLE_OBSOLETE_FUNCTIONS

#include "../cimgui/cimgui.h"

#endif // CIMGUI_UMBRELLA_HEADER
