#ifndef CIMGUI_HEADER_SHIMS
#define CIMGUI_HEADER_SHIMS

#define CIMGUI_DEFINE_ENUMS_AND_STRUCTS
#define CIMGUI_NO_EXPORT
#define IMGUI_DISABLE_OBSOLETE_FUNCTIONS

#include "../cimgui/cimgui.h"

#endif //CIMGUI_HEADER_SHIMS
