// -- THIS FILE IS AUTOGENERATED - DO NOT EDIT!!! ---

import CImGUI

@inlinable public func AlignTextToFramePadding() -> Void {
	igAlignTextToFramePadding()
}

@inlinable public func BeginChildFrame(id: ImGuiID, size: ImVec2, flags: ImGuiWindowFlags) -> Void {
	igBeginChildFrame(id,size,flags)
}

@inlinable public func BeginChildID(id: ImGuiID, size: ImVec2, border: Bool, flags: ImGuiWindowFlags) -> Void {
	igBeginChildID(id,size,border,flags)
}

@inlinable public func BeginDragDropSource(flags: ImGuiDragDropFlags) -> Void {
	igBeginDragDropSource(flags)
}

@inlinable public func BeginDragDropTarget() -> Void {
	igBeginDragDropTarget()
}

@inlinable public func BeginGroup() -> Void {
	igBeginGroup()
}

@inlinable public func BeginMainMenuBar() -> Void {
	igBeginMainMenuBar()
}

@inlinable public func BeginMenuBar() -> Void {
	igBeginMenuBar()
}

@inlinable public func BeginTooltip() -> Void {
	igBeginTooltip()
}

@inlinable public func Bullet() -> Void {
	igBullet()
}

@inlinable public func CalcItemWidth() -> Void {
	igCalcItemWidth()
}

@inlinable public func CaptureKeyboardFromApp(want_capture_keyboard_value: Bool) -> Void {
	igCaptureKeyboardFromApp(want_capture_keyboard_value)
}

@inlinable public func CaptureMouseFromApp(want_capture_mouse_value: Bool) -> Void {
	igCaptureMouseFromApp(want_capture_mouse_value)
}

@inlinable public func CloseCurrentPopup() -> Void {
	igCloseCurrentPopup()
}

@inlinable public func ColorConvertFloat4ToU32(`in`: ImVec4) -> Void {
	igColorConvertFloat4ToU32(`in`)
}

@inlinable public func ColorConvertHSVtoRGB(h: Float, s: Float, v: Float, out_r: inout Float, out_g: inout Float, out_b: inout Float) -> Void {
	igColorConvertHSVtoRGB(h,s,v,out_r,out_g,out_b)
}

@inlinable public func ColorConvertRGBtoHSV(r: Float, g: Float, b: Float, out_h: inout Float, out_s: inout Float, out_v: inout Float) -> Void {
	igColorConvertRGBtoHSV(r,g,b,out_h,out_s,out_v)
}

@inlinable public func ColorConvertU32ToFloat4(`in`: ImU32) -> Void {
	igColorConvertU32ToFloat4(`in`)
}

@inlinable public func ColorConvertU32ToFloat4_nonUDT2(`in`: ImU32) -> Void {
	igColorConvertU32ToFloat4_nonUDT2(`in`)
}

@inlinable public func DestroyPlatformWindows() -> Void {
	igDestroyPlatformWindows()
}

@inlinable public func Dummy(size: ImVec2) -> Void {
	igDummy(size)
}

@inlinable public func End() -> Void {
	igEnd()
}

@inlinable public func EndChild() -> Void {
	igEndChild()
}

@inlinable public func EndChildFrame() -> Void {
	igEndChildFrame()
}

@inlinable public func EndCombo() -> Void {
	igEndCombo()
}

@inlinable public func EndDragDropSource() -> Void {
	igEndDragDropSource()
}

@inlinable public func EndDragDropTarget() -> Void {
	igEndDragDropTarget()
}

@inlinable public func EndFrame() -> Void {
	igEndFrame()
}

@inlinable public func EndGroup() -> Void {
	igEndGroup()
}

@inlinable public func EndMainMenuBar() -> Void {
	igEndMainMenuBar()
}

@inlinable public func EndMenu() -> Void {
	igEndMenu()
}

@inlinable public func EndMenuBar() -> Void {
	igEndMenuBar()
}

@inlinable public func EndPopup() -> Void {
	igEndPopup()
}

@inlinable public func EndTabBar() -> Void {
	igEndTabBar()
}

@inlinable public func EndTabItem() -> Void {
	igEndTabItem()
}

@inlinable public func EndTooltip() -> Void {
	igEndTooltip()
}

@inlinable public func FindViewportByID(id: ImGuiID) -> Void {
	igFindViewportByID(id)
}

@inlinable public func GetBackgroundDrawList() -> Void {
	igGetBackgroundDrawList()
}

@inlinable public func GetClipboardText() -> Void {
	igGetClipboardText()
}

@inlinable public func GetColorU32(idx: ImGuiCol, alpha_mul: Float) -> Void {
	igGetColorU32(idx,alpha_mul)
}

@inlinable public func GetColorU32U32(col: ImU32) -> Void {
	igGetColorU32U32(col)
}

@inlinable public func GetColorU32Vec4(col: ImVec4) -> Void {
	igGetColorU32Vec4(col)
}

@inlinable public func GetColumnIndex() -> Void {
	igGetColumnIndex()
}

@inlinable public func GetColumnOffset(column_index: Int32) -> Void {
	igGetColumnOffset(column_index)
}

@inlinable public func GetColumnWidth(column_index: Int32) -> Void {
	igGetColumnWidth(column_index)
}

@inlinable public func GetColumnsCount() -> Void {
	igGetColumnsCount()
}

@inlinable public func GetContentRegionAvail() -> Void {
	igGetContentRegionAvail()
}

@inlinable public func GetContentRegionAvail_nonUDT2() -> Void {
	igGetContentRegionAvail_nonUDT2()
}

@inlinable public func GetContentRegionMax() -> Void {
	igGetContentRegionMax()
}

@inlinable public func GetContentRegionMax_nonUDT2() -> Void {
	igGetContentRegionMax_nonUDT2()
}

@inlinable public func GetCurrentContext() -> Void {
	igGetCurrentContext()
}

@inlinable public func GetCursorPos() -> Void {
	igGetCursorPos()
}

@inlinable public func GetCursorPosX() -> Void {
	igGetCursorPosX()
}

@inlinable public func GetCursorPosY() -> Void {
	igGetCursorPosY()
}

@inlinable public func GetCursorPos_nonUDT2() -> Void {
	igGetCursorPos_nonUDT2()
}

@inlinable public func GetCursorScreenPos() -> Void {
	igGetCursorScreenPos()
}

@inlinable public func GetCursorScreenPos_nonUDT2() -> Void {
	igGetCursorScreenPos_nonUDT2()
}

@inlinable public func GetCursorStartPos() -> Void {
	igGetCursorStartPos()
}

@inlinable public func GetCursorStartPos_nonUDT2() -> Void {
	igGetCursorStartPos_nonUDT2()
}

@inlinable public func GetDragDropPayload() -> Void {
	igGetDragDropPayload()
}

@inlinable public func GetDrawData() -> Void {
	igGetDrawData()
}

@inlinable public func GetDrawListSharedData() -> Void {
	igGetDrawListSharedData()
}

@inlinable public func GetFont() -> Void {
	igGetFont()
}

@inlinable public func GetFontSize() -> Void {
	igGetFontSize()
}

@inlinable public func GetFontTexUvWhitePixel() -> Void {
	igGetFontTexUvWhitePixel()
}

@inlinable public func GetFontTexUvWhitePixel_nonUDT2() -> Void {
	igGetFontTexUvWhitePixel_nonUDT2()
}

@inlinable public func GetForegroundDrawList() -> Void {
	igGetForegroundDrawList()
}

@inlinable public func GetFrameCount() -> Void {
	igGetFrameCount()
}

@inlinable public func GetFrameHeight() -> Void {
	igGetFrameHeight()
}

@inlinable public func GetFrameHeightWithSpacing() -> Void {
	igGetFrameHeightWithSpacing()
}

@inlinable public func GetIO() -> Void {
	igGetIO()
}

@inlinable public func GetItemRectMax() -> Void {
	igGetItemRectMax()
}

@inlinable public func GetItemRectMax_nonUDT2() -> Void {
	igGetItemRectMax_nonUDT2()
}

@inlinable public func GetItemRectMin() -> Void {
	igGetItemRectMin()
}

@inlinable public func GetItemRectMin_nonUDT2() -> Void {
	igGetItemRectMin_nonUDT2()
}

@inlinable public func GetItemRectSize() -> Void {
	igGetItemRectSize()
}

@inlinable public func GetItemRectSize_nonUDT2() -> Void {
	igGetItemRectSize_nonUDT2()
}

@inlinable public func GetKeyIndex(imgui_key: ImGuiKey) -> Void {
	igGetKeyIndex(imgui_key)
}

@inlinable public func GetKeyPressedAmount(key_index: Int32, repeat_delay: Float, rate: Float) -> Void {
	igGetKeyPressedAmount(key_index,repeat_delay,rate)
}

@inlinable public func GetMainViewport() -> Void {
	igGetMainViewport()
}

@inlinable public func GetMouseCursor() -> Void {
	igGetMouseCursor()
}

@inlinable public func GetMouseDragDelta(button: Int32, lock_threshold: Float) -> Void {
	igGetMouseDragDelta(button,lock_threshold)
}

@inlinable public func GetMouseDragDelta_nonUDT2(button: Int32, lock_threshold: Float) -> Void {
	igGetMouseDragDelta_nonUDT2(button,lock_threshold)
}

@inlinable public func GetMousePos() -> Void {
	igGetMousePos()
}

@inlinable public func GetMousePosOnOpeningCurrentPopup() -> Void {
	igGetMousePosOnOpeningCurrentPopup()
}

@inlinable public func GetMousePosOnOpeningCurrentPopup_nonUDT2() -> Void {
	igGetMousePosOnOpeningCurrentPopup_nonUDT2()
}

@inlinable public func GetMousePos_nonUDT2() -> Void {
	igGetMousePos_nonUDT2()
}

@inlinable public func GetPlatformIO() -> Void {
	igGetPlatformIO()
}

@inlinable public func GetScrollMaxX() -> Void {
	igGetScrollMaxX()
}

@inlinable public func GetScrollMaxY() -> Void {
	igGetScrollMaxY()
}

@inlinable public func GetScrollX() -> Void {
	igGetScrollX()
}

@inlinable public func GetScrollY() -> Void {
	igGetScrollY()
}

@inlinable public func GetStateStorage() -> Void {
	igGetStateStorage()
}

@inlinable public func GetStyle() -> Void {
	igGetStyle()
}

@inlinable public func GetStyleColorName(idx: ImGuiCol) -> Void {
	igGetStyleColorName(idx)
}

@inlinable public func GetStyleColorVec4(idx: ImGuiCol) -> Void {
	igGetStyleColorVec4(idx)
}

@inlinable public func GetTextLineHeight() -> Void {
	igGetTextLineHeight()
}

@inlinable public func GetTextLineHeightWithSpacing() -> Void {
	igGetTextLineHeightWithSpacing()
}

@inlinable public func GetTime() -> Void {
	igGetTime()
}

@inlinable public func GetTreeNodeToLabelSpacing() -> Void {
	igGetTreeNodeToLabelSpacing()
}

@inlinable public func GetVersion() -> Void {
	igGetVersion()
}

@inlinable public func GetWindowContentRegionMax() -> Void {
	igGetWindowContentRegionMax()
}

@inlinable public func GetWindowContentRegionMax_nonUDT2() -> Void {
	igGetWindowContentRegionMax_nonUDT2()
}

@inlinable public func GetWindowContentRegionMin() -> Void {
	igGetWindowContentRegionMin()
}

@inlinable public func GetWindowContentRegionMin_nonUDT2() -> Void {
	igGetWindowContentRegionMin_nonUDT2()
}

@inlinable public func GetWindowContentRegionWidth() -> Void {
	igGetWindowContentRegionWidth()
}

@inlinable public func GetWindowDockID() -> Void {
	igGetWindowDockID()
}

@inlinable public func GetWindowDpiScale() -> Void {
	igGetWindowDpiScale()
}

@inlinable public func GetWindowDrawList() -> Void {
	igGetWindowDrawList()
}

@inlinable public func GetWindowHeight() -> Void {
	igGetWindowHeight()
}

@inlinable public func GetWindowPos() -> Void {
	igGetWindowPos()
}

@inlinable public func GetWindowPos_nonUDT2() -> Void {
	igGetWindowPos_nonUDT2()
}

@inlinable public func GetWindowSize() -> Void {
	igGetWindowSize()
}

@inlinable public func GetWindowSize_nonUDT2() -> Void {
	igGetWindowSize_nonUDT2()
}

@inlinable public func GetWindowViewport() -> Void {
	igGetWindowViewport()
}

@inlinable public func GetWindowWidth() -> Void {
	igGetWindowWidth()
}

@inlinable public func Image(user_texture_id: ImTextureID, size: ImVec2, uv0: ImVec2, uv1: ImVec2, tint_col: ImVec4, border_col: ImVec4) -> Void {
	igImage(user_texture_id,size,uv0,uv1,tint_col,border_col)
}

@inlinable public func ImageButton(user_texture_id: ImTextureID, size: ImVec2, uv0: ImVec2, uv1: ImVec2, frame_padding: Int32, bg_col: ImVec4, tint_col: ImVec4) -> Void {
	igImageButton(user_texture_id,size,uv0,uv1,frame_padding,bg_col,tint_col)
}

@inlinable public func Indent(indent_w: Float) -> Void {
	igIndent(indent_w)
}

@inlinable public func IsAnyItemActive() -> Void {
	igIsAnyItemActive()
}

@inlinable public func IsAnyItemFocused() -> Void {
	igIsAnyItemFocused()
}

@inlinable public func IsAnyItemHovered() -> Void {
	igIsAnyItemHovered()
}

@inlinable public func IsAnyMouseDown() -> Void {
	igIsAnyMouseDown()
}

@inlinable public func IsItemActivated() -> Void {
	igIsItemActivated()
}

@inlinable public func IsItemActive() -> Void {
	igIsItemActive()
}

@inlinable public func IsItemClicked(mouse_button: Int32) -> Void {
	igIsItemClicked(mouse_button)
}

@inlinable public func IsItemDeactivated() -> Void {
	igIsItemDeactivated()
}

@inlinable public func IsItemDeactivatedAfterEdit() -> Void {
	igIsItemDeactivatedAfterEdit()
}

@inlinable public func IsItemEdited() -> Void {
	igIsItemEdited()
}

@inlinable public func IsItemFocused() -> Void {
	igIsItemFocused()
}

@inlinable public func IsItemHovered(flags: ImGuiHoveredFlags) -> Void {
	igIsItemHovered(flags)
}

@inlinable public func IsItemVisible() -> Void {
	igIsItemVisible()
}

@inlinable public func IsKeyDown(user_key_index: Int32) -> Void {
	igIsKeyDown(user_key_index)
}

@inlinable public func IsKeyPressed(user_key_index: Int32, `repeat`: Bool) -> Void {
	igIsKeyPressed(user_key_index,`repeat`)
}

@inlinable public func IsKeyReleased(user_key_index: Int32) -> Void {
	igIsKeyReleased(user_key_index)
}

@inlinable public func IsMouseClicked(button: Int32, `repeat`: Bool) -> Void {
	igIsMouseClicked(button,`repeat`)
}

@inlinable public func IsMouseDoubleClicked(button: Int32) -> Void {
	igIsMouseDoubleClicked(button)
}

@inlinable public func IsMouseDown(button: Int32) -> Void {
	igIsMouseDown(button)
}

@inlinable public func IsMouseDragging(button: Int32, lock_threshold: Float) -> Void {
	igIsMouseDragging(button,lock_threshold)
}

@inlinable public func IsMouseHoveringRect(r_min: ImVec2, r_max: ImVec2, clip: Bool) -> Void {
	igIsMouseHoveringRect(r_min,r_max,clip)
}

@inlinable public func IsMouseReleased(button: Int32) -> Void {
	igIsMouseReleased(button)
}

@inlinable public func IsRectVisible(size: ImVec2) -> Void {
	igIsRectVisible(size)
}

@inlinable public func IsRectVisibleVec2(rect_min: ImVec2, rect_max: ImVec2) -> Void {
	igIsRectVisibleVec2(rect_min,rect_max)
}

@inlinable public func IsWindowAppearing() -> Void {
	igIsWindowAppearing()
}

@inlinable public func IsWindowCollapsed() -> Void {
	igIsWindowCollapsed()
}

@inlinable public func IsWindowDocked() -> Void {
	igIsWindowDocked()
}

@inlinable public func IsWindowFocused(flags: ImGuiFocusedFlags) -> Void {
	igIsWindowFocused(flags)
}

@inlinable public func IsWindowHovered(flags: ImGuiHoveredFlags) -> Void {
	igIsWindowHovered(flags)
}

@inlinable public func ListBoxFooter() -> Void {
	igListBoxFooter()
}

@inlinable public func LogButtons() -> Void {
	igLogButtons()
}

@inlinable public func LogFinish() -> Void {
	igLogFinish()
}

@inlinable public func LogToClipboard(auto_open_depth: Int32) -> Void {
	igLogToClipboard(auto_open_depth)
}

@inlinable public func LogToTTY(auto_open_depth: Int32) -> Void {
	igLogToTTY(auto_open_depth)
}

@inlinable public func MemAlloc(size: Int) -> Void {
	igMemAlloc(size)
}

@inlinable public func NewFrame() -> Void {
	igNewFrame()
}

@inlinable public func NewLine() -> Void {
	igNewLine()
}

@inlinable public func NextColumn() -> Void {
	igNextColumn()
}

@inlinable public func PopAllowKeyboardFocus() -> Void {
	igPopAllowKeyboardFocus()
}

@inlinable public func PopButtonRepeat() -> Void {
	igPopButtonRepeat()
}

@inlinable public func PopClipRect() -> Void {
	igPopClipRect()
}

@inlinable public func PopFont() -> Void {
	igPopFont()
}

@inlinable public func PopID() -> Void {
	igPopID()
}

@inlinable public func PopItemWidth() -> Void {
	igPopItemWidth()
}

@inlinable public func PopStyleColor(count: Int32) -> Void {
	igPopStyleColor(count)
}

@inlinable public func PopStyleVar(count: Int32) -> Void {
	igPopStyleVar(count)
}

@inlinable public func PopTextWrapPos() -> Void {
	igPopTextWrapPos()
}

@inlinable public func PushAllowKeyboardFocus(allow_keyboard_focus: Bool) -> Void {
	igPushAllowKeyboardFocus(allow_keyboard_focus)
}

@inlinable public func PushButtonRepeat(`repeat`: Bool) -> Void {
	igPushButtonRepeat(`repeat`)
}

@inlinable public func PushClipRect(clip_rect_min: ImVec2, clip_rect_max: ImVec2, intersect_with_current_clip_rect: Bool) -> Void {
	igPushClipRect(clip_rect_min,clip_rect_max,intersect_with_current_clip_rect)
}

@inlinable public func PushIDInt(int_id: Int32) -> Void {
	igPushIDInt(int_id)
}

@inlinable public func PushItemWidth(item_width: Float) -> Void {
	igPushItemWidth(item_width)
}

@inlinable public func PushStyleColor(idx: ImGuiCol, col: ImVec4) -> Void {
	igPushStyleColor(idx,col)
}

@inlinable public func PushStyleColorU32(idx: ImGuiCol, col: ImU32) -> Void {
	igPushStyleColorU32(idx,col)
}

@inlinable public func PushStyleVarFloat(idx: ImGuiStyleVar, val: Float) -> Void {
	igPushStyleVarFloat(idx,val)
}

@inlinable public func PushStyleVarVec2(idx: ImGuiStyleVar, val: ImVec2) -> Void {
	igPushStyleVarVec2(idx,val)
}

@inlinable public func PushTextWrapPos(wrap_local_pos_x: Float) -> Void {
	igPushTextWrapPos(wrap_local_pos_x)
}

@inlinable public func Render() -> Void {
	igRender()
}

@inlinable public func ResetMouseDragDelta(button: Int32) -> Void {
	igResetMouseDragDelta(button)
}

@inlinable public func SameLine(offset_from_start_x: Float, spacing: Float) -> Void {
	igSameLine(offset_from_start_x,spacing)
}

@inlinable public func Separator() -> Void {
	igSeparator()
}

@inlinable public func SetColorEditOptions(flags: ImGuiColorEditFlags) -> Void {
	igSetColorEditOptions(flags)
}

@inlinable public func SetColumnOffset(column_index: Int32, offset_x: Float) -> Void {
	igSetColumnOffset(column_index,offset_x)
}

@inlinable public func SetColumnWidth(column_index: Int32, width: Float) -> Void {
	igSetColumnWidth(column_index,width)
}

@inlinable public func SetCursorPos(local_pos: ImVec2) -> Void {
	igSetCursorPos(local_pos)
}

@inlinable public func SetCursorPosX(local_x: Float) -> Void {
	igSetCursorPosX(local_x)
}

@inlinable public func SetCursorPosY(local_y: Float) -> Void {
	igSetCursorPosY(local_y)
}

@inlinable public func SetCursorScreenPos(pos: ImVec2) -> Void {
	igSetCursorScreenPos(pos)
}

@inlinable public func SetItemAllowOverlap() -> Void {
	igSetItemAllowOverlap()
}

@inlinable public func SetItemDefaultFocus() -> Void {
	igSetItemDefaultFocus()
}

@inlinable public func SetKeyboardFocusHere(offset: Int32) -> Void {
	igSetKeyboardFocusHere(offset)
}

@inlinable public func SetMouseCursor(type: ImGuiMouseCursor) -> Void {
	igSetMouseCursor(type)
}

@inlinable public func SetNextItemOpen(is_open: Bool, cond: ImGuiCond) -> Void {
	igSetNextItemOpen(is_open,cond)
}

@inlinable public func SetNextItemWidth(item_width: Float) -> Void {
	igSetNextItemWidth(item_width)
}

@inlinable public func SetNextWindowBgAlpha(alpha: Float) -> Void {
	igSetNextWindowBgAlpha(alpha)
}

@inlinable public func SetNextWindowCollapsed(collapsed: Bool, cond: ImGuiCond) -> Void {
	igSetNextWindowCollapsed(collapsed,cond)
}

@inlinable public func SetNextWindowContentSize(size: ImVec2) -> Void {
	igSetNextWindowContentSize(size)
}

@inlinable public func SetNextWindowDockID(dock_id: ImGuiID, cond: ImGuiCond) -> Void {
	igSetNextWindowDockID(dock_id,cond)
}

@inlinable public func SetNextWindowFocus() -> Void {
	igSetNextWindowFocus()
}

@inlinable public func SetNextWindowPos(pos: ImVec2, cond: ImGuiCond, pivot: ImVec2) -> Void {
	igSetNextWindowPos(pos,cond,pivot)
}

@inlinable public func SetNextWindowSize(size: ImVec2, cond: ImGuiCond) -> Void {
	igSetNextWindowSize(size,cond)
}

@inlinable public func SetNextWindowViewport(viewport_id: ImGuiID) -> Void {
	igSetNextWindowViewport(viewport_id)
}

@inlinable public func SetScrollFromPosX(local_x: Float, center_x_ratio: Float) -> Void {
	igSetScrollFromPosX(local_x,center_x_ratio)
}

@inlinable public func SetScrollFromPosY(local_y: Float, center_y_ratio: Float) -> Void {
	igSetScrollFromPosY(local_y,center_y_ratio)
}

@inlinable public func SetScrollHereX(center_x_ratio: Float) -> Void {
	igSetScrollHereX(center_x_ratio)
}

@inlinable public func SetScrollHereY(center_y_ratio: Float) -> Void {
	igSetScrollHereY(center_y_ratio)
}

@inlinable public func SetScrollX(scroll_x: Float) -> Void {
	igSetScrollX(scroll_x)
}

@inlinable public func SetScrollY(scroll_y: Float) -> Void {
	igSetScrollY(scroll_y)
}

@inlinable public func SetWindowCollapsedBool(collapsed: Bool, cond: ImGuiCond) -> Void {
	igSetWindowCollapsedBool(collapsed,cond)
}

@inlinable public func SetWindowFocus() -> Void {
	igSetWindowFocus()
}

@inlinable public func SetWindowFontScale(scale: Float) -> Void {
	igSetWindowFontScale(scale)
}

@inlinable public func SetWindowPosVec2(pos: ImVec2, cond: ImGuiCond) -> Void {
	igSetWindowPosVec2(pos,cond)
}

@inlinable public func SetWindowSizeVec2(size: ImVec2, cond: ImGuiCond) -> Void {
	igSetWindowSizeVec2(size,cond)
}

@inlinable public func ShowUserGuide() -> Void {
	igShowUserGuide()
}

@inlinable public func Spacing() -> Void {
	igSpacing()
}

@inlinable public func TreePop() -> Void {
	igTreePop()
}

@inlinable public func Unindent(indent_w: Float) -> Void {
	igUnindent(indent_w)
}

@inlinable public func UpdatePlatformWindows() -> Void {
	igUpdatePlatformWindows()
}