// -- THIS FILE IS AUTOGENERATED - DO NOT EDIT!!! ---

import CImGui

// swiftlint:disable identifier_name

// Undeclared type definitions
public typealias ImDrawListSharedData = OpaquePointer
public typealias ImGuiContext = OpaquePointer


@inlinable public func ImColorHSV(_ pOut: UnsafeMutablePointer<ImColor>!, _ this: UnsafeMutablePointer<ImColor>!, _ h: Float, _ s: Float, _ v: Float, _ a: Float) -> Void {
	return ImColor_HSV(pOut,this,h,s,v,a)
}

@inlinable public func ImColorSetHSV(_ this: UnsafeMutablePointer<ImColor>!, _ h: Float, _ s: Float, _ v: Float, _ a: Float) -> Void {
	return ImColor_SetHSV(this,h,s,v,a)
}

@inlinable public func ImDrawDataClear(_ this: UnsafeMutablePointer<ImDrawData>!) -> Void {
	return ImDrawData_Clear(this)
}

@inlinable public func ImDrawDataDeIndexAllBuffers(_ this: UnsafeMutablePointer<ImDrawData>!) -> Void {
	return ImDrawData_DeIndexAllBuffers(this)
}

@inlinable public func ImDrawDataScaleClipRects(_ this: UnsafeMutablePointer<ImDrawData>!, _ fb_scale: ImVec2) -> Void {
	return ImDrawData_ScaleClipRects(this,fb_scale)
}

@inlinable public func ImDrawListAddBezierCurve(_ this: UnsafeMutablePointer<ImDrawList>!, _ p1: ImVec2, _ p2: ImVec2, _ p3: ImVec2, _ p4: ImVec2, _ col: ImU32, _ thickness: Float, _ num_segments: Int32) -> Void {
	return ImDrawList_AddBezierCurve(this,p1,p2,p3,p4,col,thickness,num_segments)
}

@inlinable public func ImDrawListAddCallback(_ this: UnsafeMutablePointer<ImDrawList>!, _ callback: @escaping ImDrawCallback, _ callback_data: UnsafeMutableRawPointer!) -> Void {
	return ImDrawList_AddCallback(this,callback,callback_data)
}

@inlinable public func ImDrawListAddCircle(_ this: UnsafeMutablePointer<ImDrawList>!, _ center: ImVec2, _ radius: Float, _ col: ImU32, _ num_segments: Int32, _ thickness: Float) -> Void {
	return ImDrawList_AddCircle(this,center,radius,col,num_segments,thickness)
}

@inlinable public func ImDrawListAddCircleFilled(_ this: UnsafeMutablePointer<ImDrawList>!, _ center: ImVec2, _ radius: Float, _ col: ImU32, _ num_segments: Int32) -> Void {
	return ImDrawList_AddCircleFilled(this,center,radius,col,num_segments)
}

@inlinable public func ImDrawListAddConvexPolyFilled(_ this: UnsafeMutablePointer<ImDrawList>!, _ points: UnsafePointer<ImVec2>!, _ num_points: Int32, _ col: ImU32) -> Void {
	return ImDrawList_AddConvexPolyFilled(this,points,num_points,col)
}

@inlinable public func ImDrawListAddDrawCmd(_ this: UnsafeMutablePointer<ImDrawList>!) -> Void {
	return ImDrawList_AddDrawCmd(this)
}

@inlinable public func ImDrawListAddImage(_ this: UnsafeMutablePointer<ImDrawList>!, _ user_texture_id: ImTextureID, _ p_min: ImVec2, _ p_max: ImVec2, _ uv_min: ImVec2, _ uv_max: ImVec2, _ col: ImU32) -> Void {
	return ImDrawList_AddImage(this,user_texture_id,p_min,p_max,uv_min,uv_max,col)
}

@inlinable public func ImDrawListAddImageQuad(_ this: UnsafeMutablePointer<ImDrawList>!, _ user_texture_id: ImTextureID, _ p1: ImVec2, _ p2: ImVec2, _ p3: ImVec2, _ p4: ImVec2, _ uv1: ImVec2, _ uv2: ImVec2, _ uv3: ImVec2, _ uv4: ImVec2, _ col: ImU32) -> Void {
	return ImDrawList_AddImageQuad(this,user_texture_id,p1,p2,p3,p4,uv1,uv2,uv3,uv4,col)
}

@inlinable public func ImDrawListAddImageRounded(_ this: UnsafeMutablePointer<ImDrawList>!, _ user_texture_id: ImTextureID, _ p_min: ImVec2, _ p_max: ImVec2, _ uv_min: ImVec2, _ uv_max: ImVec2, _ col: ImU32, _ rounding: Float, _ rounding_corners: ImDrawCornerFlags) -> Void {
	return ImDrawList_AddImageRounded(this,user_texture_id,p_min,p_max,uv_min,uv_max,col,rounding,rounding_corners)
}

@inlinable public func ImDrawListAddLine(_ this: UnsafeMutablePointer<ImDrawList>!, _ p1: ImVec2, _ p2: ImVec2, _ col: ImU32, _ thickness: Float) -> Void {
	return ImDrawList_AddLine(this,p1,p2,col,thickness)
}

@inlinable public func ImDrawListAddNgon(_ this: UnsafeMutablePointer<ImDrawList>!, _ center: ImVec2, _ radius: Float, _ col: ImU32, _ num_segments: Int32, _ thickness: Float) -> Void {
	return ImDrawList_AddNgon(this,center,radius,col,num_segments,thickness)
}

@inlinable public func ImDrawListAddNgonFilled(_ this: UnsafeMutablePointer<ImDrawList>!, _ center: ImVec2, _ radius: Float, _ col: ImU32, _ num_segments: Int32) -> Void {
	return ImDrawList_AddNgonFilled(this,center,radius,col,num_segments)
}

@inlinable public func ImDrawListAddPolyline(_ this: UnsafeMutablePointer<ImDrawList>!, _ points: UnsafePointer<ImVec2>!, _ num_points: Int32, _ col: ImU32, _ closed: Bool, _ thickness: Float) -> Void {
	return ImDrawList_AddPolyline(this,points,num_points,col,closed,thickness)
}

@inlinable public func ImDrawListAddQuad(_ this: UnsafeMutablePointer<ImDrawList>!, _ p1: ImVec2, _ p2: ImVec2, _ p3: ImVec2, _ p4: ImVec2, _ col: ImU32, _ thickness: Float) -> Void {
	return ImDrawList_AddQuad(this,p1,p2,p3,p4,col,thickness)
}

@inlinable public func ImDrawListAddQuadFilled(_ this: UnsafeMutablePointer<ImDrawList>!, _ p1: ImVec2, _ p2: ImVec2, _ p3: ImVec2, _ p4: ImVec2, _ col: ImU32) -> Void {
	return ImDrawList_AddQuadFilled(this,p1,p2,p3,p4,col)
}

@inlinable public func ImDrawListAddRect(_ this: UnsafeMutablePointer<ImDrawList>!, _ p_min: ImVec2, _ p_max: ImVec2, _ col: ImU32, _ rounding: Float, _ rounding_corners: ImDrawCornerFlags, _ thickness: Float) -> Void {
	return ImDrawList_AddRect(this,p_min,p_max,col,rounding,rounding_corners,thickness)
}

@inlinable public func ImDrawListAddRectFilled(_ this: UnsafeMutablePointer<ImDrawList>!, _ p_min: ImVec2, _ p_max: ImVec2, _ col: ImU32, _ rounding: Float, _ rounding_corners: ImDrawCornerFlags) -> Void {
	return ImDrawList_AddRectFilled(this,p_min,p_max,col,rounding,rounding_corners)
}

@inlinable public func ImDrawListAddRectFilledMultiColor(_ this: UnsafeMutablePointer<ImDrawList>!, _ p_min: ImVec2, _ p_max: ImVec2, _ col_upr_left: ImU32, _ col_upr_right: ImU32, _ col_bot_right: ImU32, _ col_bot_left: ImU32) -> Void {
	return ImDrawList_AddRectFilledMultiColor(this,p_min,p_max,col_upr_left,col_upr_right,col_bot_right,col_bot_left)
}

@inlinable public func ImDrawListAddTextFontPtr(_ this: UnsafeMutablePointer<ImDrawList>!, _ font: UnsafePointer<ImFont>!, _ font_size: Float, _ pos: ImVec2, _ col: ImU32, _ text_begin: String?, _ text_end: String?, _ wrap_width: Float, _ cpu_fine_clip_rect: UnsafePointer<ImVec4>!) -> Void {
	text_begin!.withCString { text_beginPtr in
		text_end!.withCString { text_endPtr in
			return ImDrawList_AddTextFontPtr(this,font,font_size,pos,col,text_beginPtr,text_endPtr,wrap_width,cpu_fine_clip_rect)
		}
	}
}

@inlinable public func ImDrawListAddTextVec2(_ this: UnsafeMutablePointer<ImDrawList>!, _ pos: ImVec2, _ col: ImU32, _ text_begin: String?, _ text_end: String?) -> Void {
	text_begin!.withCString { text_beginPtr in
		text_end!.withCString { text_endPtr in
			return ImDrawList_AddTextVec2(this,pos,col,text_beginPtr,text_endPtr)
		}
	}
}

@inlinable public func ImDrawListAddTriangle(_ this: UnsafeMutablePointer<ImDrawList>!, _ p1: ImVec2, _ p2: ImVec2, _ p3: ImVec2, _ col: ImU32, _ thickness: Float) -> Void {
	return ImDrawList_AddTriangle(this,p1,p2,p3,col,thickness)
}

@inlinable public func ImDrawListAddTriangleFilled(_ this: UnsafeMutablePointer<ImDrawList>!, _ p1: ImVec2, _ p2: ImVec2, _ p3: ImVec2, _ col: ImU32) -> Void {
	return ImDrawList_AddTriangleFilled(this,p1,p2,p3,col)
}

@inlinable public func ImDrawListChannelsMerge(_ this: UnsafeMutablePointer<ImDrawList>!) -> Void {
	return ImDrawList_ChannelsMerge(this)
}

@inlinable public func ImDrawListChannelsSetCurrent(_ this: UnsafeMutablePointer<ImDrawList>!, _ n: Int32) -> Void {
	return ImDrawList_ChannelsSetCurrent(this,n)
}

@inlinable public func ImDrawListChannelsSplit(_ this: UnsafeMutablePointer<ImDrawList>!, _ count: Int32) -> Void {
	return ImDrawList_ChannelsSplit(this,count)
}

@inlinable public func ImDrawListClear(_ this: UnsafeMutablePointer<ImDrawList>!) -> Void {
	return ImDrawList_Clear(this)
}

@inlinable public func ImDrawListClearFreeMemory(_ this: UnsafeMutablePointer<ImDrawList>!) -> Void {
	return ImDrawList_ClearFreeMemory(this)
}

@inlinable public func ImDrawListCloneOutput(_ this: UnsafeMutablePointer<ImDrawList>!) -> UnsafeMutablePointer<ImDrawList>! {
	return ImDrawList_CloneOutput(this)
}

@inlinable public func ImDrawListGetClipRectMax(_ pOut: UnsafeMutablePointer<ImVec2>!, _ this: UnsafeMutablePointer<ImDrawList>!) -> Void {
	return ImDrawList_GetClipRectMax(pOut,this)
}

@inlinable public func ImDrawListGetClipRectMin(_ pOut: UnsafeMutablePointer<ImVec2>!, _ this: UnsafeMutablePointer<ImDrawList>!) -> Void {
	return ImDrawList_GetClipRectMin(pOut,this)
}

@inlinable public func ImDrawListPathArcTo(_ this: UnsafeMutablePointer<ImDrawList>!, _ center: ImVec2, _ radius: Float, _ a_min: Float, _ a_max: Float, _ num_segments: Int32) -> Void {
	return ImDrawList_PathArcTo(this,center,radius,a_min,a_max,num_segments)
}

@inlinable public func ImDrawListPathArcToFast(_ this: UnsafeMutablePointer<ImDrawList>!, _ center: ImVec2, _ radius: Float, _ a_min_of_12: Int32, _ a_max_of_12: Int32) -> Void {
	return ImDrawList_PathArcToFast(this,center,radius,a_min_of_12,a_max_of_12)
}

@inlinable public func ImDrawListPathBezierCurveTo(_ this: UnsafeMutablePointer<ImDrawList>!, _ p2: ImVec2, _ p3: ImVec2, _ p4: ImVec2, _ num_segments: Int32) -> Void {
	return ImDrawList_PathBezierCurveTo(this,p2,p3,p4,num_segments)
}

@inlinable public func ImDrawListPathClear(_ this: UnsafeMutablePointer<ImDrawList>!) -> Void {
	return ImDrawList_PathClear(this)
}

@inlinable public func ImDrawListPathFillConvex(_ this: UnsafeMutablePointer<ImDrawList>!, _ col: ImU32) -> Void {
	return ImDrawList_PathFillConvex(this,col)
}

@inlinable public func ImDrawListPathLineTo(_ this: UnsafeMutablePointer<ImDrawList>!, _ pos: ImVec2) -> Void {
	return ImDrawList_PathLineTo(this,pos)
}

@inlinable public func ImDrawListPathLineToMergeDuplicate(_ this: UnsafeMutablePointer<ImDrawList>!, _ pos: ImVec2) -> Void {
	return ImDrawList_PathLineToMergeDuplicate(this,pos)
}

@inlinable public func ImDrawListPathRect(_ this: UnsafeMutablePointer<ImDrawList>!, _ rect_min: ImVec2, _ rect_max: ImVec2, _ rounding: Float, _ rounding_corners: ImDrawCornerFlags) -> Void {
	return ImDrawList_PathRect(this,rect_min,rect_max,rounding,rounding_corners)
}

@inlinable public func ImDrawListPathStroke(_ this: UnsafeMutablePointer<ImDrawList>!, _ col: ImU32, _ closed: Bool, _ thickness: Float) -> Void {
	return ImDrawList_PathStroke(this,col,closed,thickness)
}

@inlinable public func ImDrawListPopClipRect(_ this: UnsafeMutablePointer<ImDrawList>!) -> Void {
	return ImDrawList_PopClipRect(this)
}

@inlinable public func ImDrawListPopTextureID(_ this: UnsafeMutablePointer<ImDrawList>!) -> Void {
	return ImDrawList_PopTextureID(this)
}

@inlinable public func ImDrawListPrimQuadUV(_ this: UnsafeMutablePointer<ImDrawList>!, _ a: ImVec2, _ b: ImVec2, _ c: ImVec2, _ d: ImVec2, _ uv_a: ImVec2, _ uv_b: ImVec2, _ uv_c: ImVec2, _ uv_d: ImVec2, _ col: ImU32) -> Void {
	return ImDrawList_PrimQuadUV(this,a,b,c,d,uv_a,uv_b,uv_c,uv_d,col)
}

@inlinable public func ImDrawListPrimRect(_ this: UnsafeMutablePointer<ImDrawList>!, _ a: ImVec2, _ b: ImVec2, _ col: ImU32) -> Void {
	return ImDrawList_PrimRect(this,a,b,col)
}

@inlinable public func ImDrawListPrimRectUV(_ this: UnsafeMutablePointer<ImDrawList>!, _ a: ImVec2, _ b: ImVec2, _ uv_a: ImVec2, _ uv_b: ImVec2, _ col: ImU32) -> Void {
	return ImDrawList_PrimRectUV(this,a,b,uv_a,uv_b,col)
}

@inlinable public func ImDrawListPrimReserve(_ this: UnsafeMutablePointer<ImDrawList>!, _ idx_count: Int32, _ vtx_count: Int32) -> Void {
	return ImDrawList_PrimReserve(this,idx_count,vtx_count)
}

@inlinable public func ImDrawListPrimUnreserve(_ this: UnsafeMutablePointer<ImDrawList>!, _ idx_count: Int32, _ vtx_count: Int32) -> Void {
	return ImDrawList_PrimUnreserve(this,idx_count,vtx_count)
}

@inlinable public func ImDrawListPrimVtx(_ this: UnsafeMutablePointer<ImDrawList>!, _ pos: ImVec2, _ uv: ImVec2, _ col: ImU32) -> Void {
	return ImDrawList_PrimVtx(this,pos,uv,col)
}

@inlinable public func ImDrawListPrimWriteIdx(_ this: UnsafeMutablePointer<ImDrawList>!, _ idx: ImDrawIdx) -> Void {
	return ImDrawList_PrimWriteIdx(this,idx)
}

@inlinable public func ImDrawListPrimWriteVtx(_ this: UnsafeMutablePointer<ImDrawList>!, _ pos: ImVec2, _ uv: ImVec2, _ col: ImU32) -> Void {
	return ImDrawList_PrimWriteVtx(this,pos,uv,col)
}

@inlinable public func ImDrawListPushClipRect(_ this: UnsafeMutablePointer<ImDrawList>!, _ clip_rect_min: ImVec2, _ clip_rect_max: ImVec2, _ intersect_with_current_clip_rect: Bool) -> Void {
	return ImDrawList_PushClipRect(this,clip_rect_min,clip_rect_max,intersect_with_current_clip_rect)
}

@inlinable public func ImDrawListPushClipRectFullScreen(_ this: UnsafeMutablePointer<ImDrawList>!) -> Void {
	return ImDrawList_PushClipRectFullScreen(this)
}

@inlinable public func ImDrawListPushTextureID(_ this: UnsafeMutablePointer<ImDrawList>!, _ texture_id: ImTextureID) -> Void {
	return ImDrawList_PushTextureID(this,texture_id)
}

@inlinable public func ImDrawListSplitterClear(_ this: UnsafeMutablePointer<ImDrawListSplitter>!) -> Void {
	return ImDrawListSplitter_Clear(this)
}

@inlinable public func ImDrawListSplitterClearFreeMemory(_ this: UnsafeMutablePointer<ImDrawListSplitter>!) -> Void {
	return ImDrawListSplitter_ClearFreeMemory(this)
}

@inlinable public func ImDrawListSplitterMerge(_ this: UnsafeMutablePointer<ImDrawListSplitter>!, _ draw_list: UnsafeMutablePointer<ImDrawList>!) -> Void {
	return ImDrawListSplitter_Merge(this,draw_list)
}

@inlinable public func ImDrawListSplitterSetCurrentChannel(_ this: UnsafeMutablePointer<ImDrawListSplitter>!, _ draw_list: UnsafeMutablePointer<ImDrawList>!, _ channel_idx: Int32) -> Void {
	return ImDrawListSplitter_SetCurrentChannel(this,draw_list,channel_idx)
}

@inlinable public func ImDrawListSplitterSplit(_ this: UnsafeMutablePointer<ImDrawListSplitter>!, _ draw_list: UnsafeMutablePointer<ImDrawList>!, _ count: Int32) -> Void {
	return ImDrawListSplitter_Split(this,draw_list,count)
}

@inlinable public func ImDrawListUpdateClipRect(_ this: UnsafeMutablePointer<ImDrawList>!) -> Void {
	return ImDrawList_UpdateClipRect(this)
}

@inlinable public func ImDrawListUpdateTextureID(_ this: UnsafeMutablePointer<ImDrawList>!) -> Void {
	return ImDrawList_UpdateTextureID(this)
}

@inlinable public func ImFontAddGlyph(_ this: UnsafeMutablePointer<ImFont>!, _ c: ImWchar, _ x0: Float, _ y0: Float, _ x1: Float, _ y1: Float, _ u0: Float, _ v0: Float, _ u1: Float, _ v1: Float, _ advance_x: Float) -> Void {
	return ImFont_AddGlyph(this,c,x0,y0,x1,y1,u0,v0,u1,v1,advance_x)
}

@inlinable public func ImFontAddRemapChar(_ this: UnsafeMutablePointer<ImFont>!, _ dst: ImWchar, _ src: ImWchar, _ overwrite_dst: Bool) -> Void {
	return ImFont_AddRemapChar(this,dst,src,overwrite_dst)
}

@inlinable public func ImFontAtlasAddCustomRectFontGlyph(_ this: UnsafeMutablePointer<ImFontAtlas>!, _ font: UnsafeMutablePointer<ImFont>!, _ id: ImWchar, _ width: Int32, _ height: Int32, _ advance_x: Float, _ offset: ImVec2) -> Int32 {
	return ImFontAtlas_AddCustomRectFontGlyph(this,font,id,width,height,advance_x,offset)
}

@inlinable public func ImFontAtlasAddCustomRectRegular(_ this: UnsafeMutablePointer<ImFontAtlas>!, _ id: UInt32, _ width: Int32, _ height: Int32) -> Int32 {
	return ImFontAtlas_AddCustomRectRegular(this,id,width,height)
}

@inlinable public func ImFontAtlasAddFont(_ this: UnsafeMutablePointer<ImFontAtlas>!, _ font_cfg: UnsafePointer<ImFontConfig>!) -> UnsafeMutablePointer<ImFont>! {
	return ImFontAtlas_AddFont(this,font_cfg)
}

@inlinable public func ImFontAtlasAddFontDefault(_ this: UnsafeMutablePointer<ImFontAtlas>!, _ font_cfg: UnsafePointer<ImFontConfig>!) -> UnsafeMutablePointer<ImFont>! {
	return ImFontAtlas_AddFontDefault(this,font_cfg)
}

@inlinable public func ImFontAtlasAddFontFromFileTTF(_ this: UnsafeMutablePointer<ImFontAtlas>!, _ filename: String?, _ size_pixels: Float, _ font_cfg: UnsafePointer<ImFontConfig>!, _ glyph_ranges: UnsafePointer<ImWchar>!) -> UnsafeMutablePointer<ImFont>! {
	filename!.withCString { filenamePtr in
		return ImFontAtlas_AddFontFromFileTTF(this,filenamePtr,size_pixels,font_cfg,glyph_ranges)
	}
}

@inlinable public func ImFontAtlasAddFontFromMemoryCompressedBase85TTF(_ this: UnsafeMutablePointer<ImFontAtlas>!, _ compressed_font_data_base85: String?, _ size_pixels: Float, _ font_cfg: UnsafePointer<ImFontConfig>!, _ glyph_ranges: UnsafePointer<ImWchar>!) -> UnsafeMutablePointer<ImFont>! {
	compressed_font_data_base85!.withCString { compressed_font_data_base85Ptr in
		return ImFontAtlas_AddFontFromMemoryCompressedBase85TTF(this,compressed_font_data_base85Ptr,size_pixels,font_cfg,glyph_ranges)
	}
}

@inlinable public func ImFontAtlasAddFontFromMemoryCompressedTTF(_ this: UnsafeMutablePointer<ImFontAtlas>!, _ compressed_font_data: UnsafeRawPointer!, _ compressed_font_size: Int32, _ size_pixels: Float, _ font_cfg: UnsafePointer<ImFontConfig>!, _ glyph_ranges: UnsafePointer<ImWchar>!) -> UnsafeMutablePointer<ImFont>! {
	return ImFontAtlas_AddFontFromMemoryCompressedTTF(this,compressed_font_data,compressed_font_size,size_pixels,font_cfg,glyph_ranges)
}

@inlinable public func ImFontAtlasAddFontFromMemoryTTF(_ this: UnsafeMutablePointer<ImFontAtlas>!, _ font_data: UnsafeMutableRawPointer!, _ font_size: Int32, _ size_pixels: Float, _ font_cfg: UnsafePointer<ImFontConfig>!, _ glyph_ranges: UnsafePointer<ImWchar>!) -> UnsafeMutablePointer<ImFont>! {
	return ImFontAtlas_AddFontFromMemoryTTF(this,font_data,font_size,size_pixels,font_cfg,glyph_ranges)
}

@inlinable @discardableResult public func ImFontAtlasBuild(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> Bool {
	return ImFontAtlas_Build(this)
}

@inlinable public func ImFontAtlasCalcCustomRectUV(_ this: UnsafeMutablePointer<ImFontAtlas>!, _ rect: UnsafePointer<ImFontAtlasCustomRect>!, _ out_uv_min: UnsafeMutablePointer<ImVec2>!, _ out_uv_max: UnsafeMutablePointer<ImVec2>!) -> Void {
	return ImFontAtlas_CalcCustomRectUV(this,rect,out_uv_min,out_uv_max)
}

@inlinable public func ImFontAtlasClear(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> Void {
	return ImFontAtlas_Clear(this)
}

@inlinable public func ImFontAtlasClearFonts(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> Void {
	return ImFontAtlas_ClearFonts(this)
}

@inlinable public func ImFontAtlasClearInputData(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> Void {
	return ImFontAtlas_ClearInputData(this)
}

@inlinable public func ImFontAtlasClearTexData(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> Void {
	return ImFontAtlas_ClearTexData(this)
}

@inlinable @discardableResult public func ImFontAtlasCustomRectIsPacked(_ this: UnsafeMutablePointer<ImFontAtlasCustomRect>!) -> Bool {
	return ImFontAtlasCustomRect_IsPacked(this)
}

@inlinable public func ImFontAtlasGetCustomRectByIndex(_ this: UnsafeMutablePointer<ImFontAtlas>!, _ index: Int32) -> UnsafePointer<ImFontAtlasCustomRect>! {
	return ImFontAtlas_GetCustomRectByIndex(this,index)
}

@inlinable public func ImFontAtlasGetGlyphRangesChineseFull(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> UnsafePointer<ImWchar>! {
	return ImFontAtlas_GetGlyphRangesChineseFull(this)
}

@inlinable public func ImFontAtlasGetGlyphRangesChineseSimplifiedCommon(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> UnsafePointer<ImWchar>! {
	return ImFontAtlas_GetGlyphRangesChineseSimplifiedCommon(this)
}

@inlinable public func ImFontAtlasGetGlyphRangesCyrillic(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> UnsafePointer<ImWchar>! {
	return ImFontAtlas_GetGlyphRangesCyrillic(this)
}

@inlinable public func ImFontAtlasGetGlyphRangesDefault(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> UnsafePointer<ImWchar>! {
	return ImFontAtlas_GetGlyphRangesDefault(this)
}

@inlinable public func ImFontAtlasGetGlyphRangesJapanese(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> UnsafePointer<ImWchar>! {
	return ImFontAtlas_GetGlyphRangesJapanese(this)
}

@inlinable public func ImFontAtlasGetGlyphRangesKorean(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> UnsafePointer<ImWchar>! {
	return ImFontAtlas_GetGlyphRangesKorean(this)
}

@inlinable public func ImFontAtlasGetGlyphRangesThai(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> UnsafePointer<ImWchar>! {
	return ImFontAtlas_GetGlyphRangesThai(this)
}

@inlinable public func ImFontAtlasGetGlyphRangesVietnamese(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> UnsafePointer<ImWchar>! {
	return ImFontAtlas_GetGlyphRangesVietnamese(this)
}

@inlinable @discardableResult public func ImFontAtlasGetMouseCursorTexData(_ this: UnsafeMutablePointer<ImFontAtlas>!, _ cursor: ImGuiMouseCursor, _ out_offset: UnsafeMutablePointer<ImVec2>!, _ out_size: UnsafeMutablePointer<ImVec2>!, _ out_uv_border: inout (ImVec2,ImVec2), _ out_uv_fill: inout (ImVec2,ImVec2)) -> Bool {
	return ImFontAtlas_GetMouseCursorTexData(this,cursor,out_offset,out_size,UnsafeMutableBufferPointer<ImVec2>(start: &out_uv_border.0, count: 2).baseAddress!,UnsafeMutableBufferPointer<ImVec2>(start: &out_uv_fill.0, count: 2).baseAddress!)
}

@inlinable @discardableResult public func ImFontAtlasIsBuilt(_ this: UnsafeMutablePointer<ImFontAtlas>!) -> Bool {
	return ImFontAtlas_IsBuilt(this)
}

@inlinable public func ImFontAtlasSetTexID(_ this: UnsafeMutablePointer<ImFontAtlas>!, _ id: ImTextureID) -> Void {
	return ImFontAtlas_SetTexID(this,id)
}

@inlinable public func ImFontBuildLookupTable(_ this: UnsafeMutablePointer<ImFont>!) -> Void {
	return ImFont_BuildLookupTable(this)
}

@inlinable public func ImFontCalcWordWrapPositionA(_ this: UnsafeMutablePointer<ImFont>!, _ scale: Float, _ text: String?, _ text_end: String?, _ wrap_width: Float) -> String? {
	text!.withCString { textPtr in
		text_end!.withCString { text_endPtr in
			return String(cString: ImFont_CalcWordWrapPositionA(this,scale,textPtr,text_endPtr,wrap_width))
		}
	}
}

@inlinable public func ImFontClearOutputData(_ this: UnsafeMutablePointer<ImFont>!) -> Void {
	return ImFont_ClearOutputData(this)
}

@inlinable public func ImFontFindGlyph(_ this: UnsafeMutablePointer<ImFont>!, _ c: ImWchar) -> UnsafePointer<ImFontGlyph>! {
	return ImFont_FindGlyph(this,c)
}

@inlinable public func ImFontFindGlyphNoFallback(_ this: UnsafeMutablePointer<ImFont>!, _ c: ImWchar) -> UnsafePointer<ImFontGlyph>! {
	return ImFont_FindGlyphNoFallback(this,c)
}

@inlinable public func ImFontGetCharAdvance(_ this: UnsafeMutablePointer<ImFont>!, _ c: ImWchar) -> Float {
	return ImFont_GetCharAdvance(this,c)
}

@inlinable public func ImFontGetDebugName(_ this: UnsafeMutablePointer<ImFont>!) -> String? {
	return String(cString: ImFont_GetDebugName(this))
}

@inlinable public func ImFontGlyphRangesBuilderAddChar(_ this: UnsafeMutablePointer<ImFontGlyphRangesBuilder>!, _ c: ImWchar) -> Void {
	return ImFontGlyphRangesBuilder_AddChar(this,c)
}

@inlinable public func ImFontGlyphRangesBuilderAddRanges(_ this: UnsafeMutablePointer<ImFontGlyphRangesBuilder>!, _ ranges: UnsafePointer<ImWchar>!) -> Void {
	return ImFontGlyphRangesBuilder_AddRanges(this,ranges)
}

@inlinable public func ImFontGlyphRangesBuilderAddText(_ this: UnsafeMutablePointer<ImFontGlyphRangesBuilder>!, _ text: String?, _ text_end: String?) -> Void {
	text!.withCString { textPtr in
		text_end!.withCString { text_endPtr in
			return ImFontGlyphRangesBuilder_AddText(this,textPtr,text_endPtr)
		}
	}
}

@inlinable public func ImFontGlyphRangesBuilderBuildRanges(_ this: UnsafeMutablePointer<ImFontGlyphRangesBuilder>!, _ out_ranges: UnsafeMutablePointer<ImVector_ImWchar>!) -> Void {
	return ImFontGlyphRangesBuilder_BuildRanges(this,out_ranges)
}

@inlinable public func ImFontGlyphRangesBuilderClear(_ this: UnsafeMutablePointer<ImFontGlyphRangesBuilder>!) -> Void {
	return ImFontGlyphRangesBuilder_Clear(this)
}

@inlinable @discardableResult public func ImFontGlyphRangesBuilderGetBit(_ this: UnsafeMutablePointer<ImFontGlyphRangesBuilder>!, _ n: Int) -> Bool {
	return ImFontGlyphRangesBuilder_GetBit(this,n)
}

@inlinable public func ImFontGlyphRangesBuilderSetBit(_ this: UnsafeMutablePointer<ImFontGlyphRangesBuilder>!, _ n: Int) -> Void {
	return ImFontGlyphRangesBuilder_SetBit(this,n)
}

@inlinable public func ImFontGrowIndex(_ this: UnsafeMutablePointer<ImFont>!, _ new_size: Int32) -> Void {
	return ImFont_GrowIndex(this,new_size)
}

@inlinable @discardableResult public func ImFontIsGlyphRangeUnused(_ this: UnsafeMutablePointer<ImFont>!, _ c_begin: UInt32, _ c_last: UInt32) -> Bool {
	return ImFont_IsGlyphRangeUnused(this,c_begin,c_last)
}

@inlinable @discardableResult public func ImFontIsLoaded(_ this: UnsafeMutablePointer<ImFont>!) -> Bool {
	return ImFont_IsLoaded(this)
}

@inlinable public func ImFontRenderChar(_ this: UnsafeMutablePointer<ImFont>!, _ draw_list: UnsafeMutablePointer<ImDrawList>!, _ size: Float, _ pos: ImVec2, _ col: ImU32, _ c: ImWchar) -> Void {
	return ImFont_RenderChar(this,draw_list,size,pos,col,c)
}

@inlinable public func ImFontRenderText(_ this: UnsafeMutablePointer<ImFont>!, _ draw_list: UnsafeMutablePointer<ImDrawList>!, _ size: Float, _ pos: ImVec2, _ col: ImU32, _ clip_rect: ImVec4, _ text_begin: String?, _ text_end: String?, _ wrap_width: Float, _ cpu_fine_clip: Bool) -> Void {
	text_begin!.withCString { text_beginPtr in
		text_end!.withCString { text_endPtr in
			return ImFont_RenderText(this,draw_list,size,pos,col,clip_rect,text_beginPtr,text_endPtr,wrap_width,cpu_fine_clip)
		}
	}
}

@inlinable public func ImFontSetFallbackChar(_ this: UnsafeMutablePointer<ImFont>!, _ c: ImWchar) -> Void {
	return ImFont_SetFallbackChar(this,c)
}

@inlinable public func ImFontSetGlyphVisible(_ this: UnsafeMutablePointer<ImFont>!, _ c: ImWchar, _ visible: Bool) -> Void {
	return ImFont_SetGlyphVisible(this,c,visible)
}

@inlinable public func ImGuiAcceptDragDropPayload(_ type: String?, _ flags: ImGuiDragDropFlags) -> UnsafePointer<ImGuiPayload>! {
	type!.withCString { typePtr in
		return igAcceptDragDropPayload(typePtr,flags)
	}
}

@inlinable public func ImGuiAlignTextToFramePadding() -> Void {
	return igAlignTextToFramePadding()
}

@inlinable @discardableResult public func ImGuiArrowButton(_ str_id: String?, _ dir: ImGuiDir) -> Bool {
	str_id!.withCString { str_idPtr in
		return igArrowButton(str_idPtr,dir)
	}
}

@inlinable @discardableResult public func ImGuiBegin(_ name: String?, _ p_open: UnsafeMutablePointer<Bool>!, _ flags: ImGuiWindowFlags) -> Bool {
	name!.withCString { namePtr in
		return igBegin(namePtr,p_open,flags)
	}
}

@inlinable @discardableResult public func ImGuiBeginChildFrame(_ id: ImGuiID, _ size: ImVec2, _ flags: ImGuiWindowFlags) -> Bool {
	return igBeginChildFrame(id,size,flags)
}

@inlinable @discardableResult public func ImGuiBeginChildID(_ id: ImGuiID, _ size: ImVec2, _ border: Bool, _ flags: ImGuiWindowFlags) -> Bool {
	return igBeginChildID(id,size,border,flags)
}

@inlinable @discardableResult public func ImGuiBeginChildStr(_ str_id: String?, _ size: ImVec2, _ border: Bool, _ flags: ImGuiWindowFlags) -> Bool {
	str_id!.withCString { str_idPtr in
		return igBeginChildStr(str_idPtr,size,border,flags)
	}
}

@inlinable @discardableResult public func ImGuiBeginCombo(_ label: String?, _ preview_value: String?, _ flags: ImGuiComboFlags) -> Bool {
	label!.withCString { labelPtr in
		preview_value!.withCString { preview_valuePtr in
			return igBeginCombo(labelPtr,preview_valuePtr,flags)
		}
	}
}

@inlinable @discardableResult public func ImGuiBeginDragDropSource(_ flags: ImGuiDragDropFlags) -> Bool {
	return igBeginDragDropSource(flags)
}

@inlinable @discardableResult public func ImGuiBeginDragDropTarget() -> Bool {
	return igBeginDragDropTarget()
}

@inlinable public func ImGuiBeginGroup() -> Void {
	return igBeginGroup()
}

@inlinable @discardableResult public func ImGuiBeginMainMenuBar() -> Bool {
	return igBeginMainMenuBar()
}

@inlinable @discardableResult public func ImGuiBeginMenu(_ label: String?, _ enabled: Bool) -> Bool {
	label!.withCString { labelPtr in
		return igBeginMenu(labelPtr,enabled)
	}
}

@inlinable @discardableResult public func ImGuiBeginMenuBar() -> Bool {
	return igBeginMenuBar()
}

@inlinable @discardableResult public func ImGuiBeginPopup(_ str_id: String?, _ flags: ImGuiWindowFlags) -> Bool {
	str_id!.withCString { str_idPtr in
		return igBeginPopup(str_idPtr,flags)
	}
}

@inlinable @discardableResult public func ImGuiBeginPopupContextItem(_ str_id: String?, _ mouse_button: ImGuiMouseButton) -> Bool {
	str_id!.withCString { str_idPtr in
		return igBeginPopupContextItem(str_idPtr,mouse_button)
	}
}

@inlinable @discardableResult public func ImGuiBeginPopupContextVoid(_ str_id: String?, _ mouse_button: ImGuiMouseButton) -> Bool {
	str_id!.withCString { str_idPtr in
		return igBeginPopupContextVoid(str_idPtr,mouse_button)
	}
}

@inlinable @discardableResult public func ImGuiBeginPopupContextWindow(_ str_id: String?, _ mouse_button: ImGuiMouseButton, _ also_over_items: Bool) -> Bool {
	str_id!.withCString { str_idPtr in
		return igBeginPopupContextWindow(str_idPtr,mouse_button,also_over_items)
	}
}

@inlinable @discardableResult public func ImGuiBeginPopupModal(_ name: String?, _ p_open: UnsafeMutablePointer<Bool>!, _ flags: ImGuiWindowFlags) -> Bool {
	name!.withCString { namePtr in
		return igBeginPopupModal(namePtr,p_open,flags)
	}
}

@inlinable @discardableResult public func ImGuiBeginTabBar(_ str_id: String?, _ flags: ImGuiTabBarFlags) -> Bool {
	str_id!.withCString { str_idPtr in
		return igBeginTabBar(str_idPtr,flags)
	}
}

@inlinable @discardableResult public func ImGuiBeginTabItem(_ label: String?, _ p_open: UnsafeMutablePointer<Bool>!, _ flags: ImGuiTabItemFlags) -> Bool {
	label!.withCString { labelPtr in
		return igBeginTabItem(labelPtr,p_open,flags)
	}
}

@inlinable public func ImGuiBeginTooltip() -> Void {
	return igBeginTooltip()
}

@inlinable public func ImGuiBullet() -> Void {
	return igBullet()
}

@inlinable public func ImGuiBulletTextV(_ fmt: String?, _ args: CVarArg...) -> Void {
	fmt!.withCString { fmtPtr in
		withVaList(args) { varArgsPtr in
			return igBulletTextV(fmtPtr,varArgsPtr)
		}
	}
}

@inlinable @discardableResult public func ImGuiButton(_ label: String?, _ size: ImVec2) -> Bool {
	label!.withCString { labelPtr in
		return igButton(labelPtr,size)
	}
}

@inlinable public func ImGuiCalcItemWidth() -> Float {
	return igCalcItemWidth()
}

@inlinable public func ImGuiCalcListClipping(_ items_count: Int32, _ items_height: Float, _ out_items_display_start: UnsafeMutablePointer<Int32>!, _ out_items_display_end: UnsafeMutablePointer<Int32>!) -> Void {
	return igCalcListClipping(items_count,items_height,out_items_display_start,out_items_display_end)
}

@inlinable public func ImGuiCalcTextSize(_ pOut: UnsafeMutablePointer<ImVec2>!, _ text: String?, _ text_end: String?, _ hide_text_after_double_hash: Bool, _ wrap_width: Float) -> Void {
	text!.withCString { textPtr in
		text_end!.withCString { text_endPtr in
			return igCalcTextSize(pOut,textPtr,text_endPtr,hide_text_after_double_hash,wrap_width)
		}
	}
}

@inlinable public func ImGuiCaptureKeyboardFromApp(_ want_capture_keyboard_value: Bool) -> Void {
	return igCaptureKeyboardFromApp(want_capture_keyboard_value)
}

@inlinable public func ImGuiCaptureMouseFromApp(_ want_capture_mouse_value: Bool) -> Void {
	return igCaptureMouseFromApp(want_capture_mouse_value)
}

@inlinable @discardableResult public func ImGuiCheckbox(_ label: String?, _ v: UnsafeMutablePointer<Bool>!) -> Bool {
	label!.withCString { labelPtr in
		return igCheckbox(labelPtr,v)
	}
}

@inlinable @discardableResult public func ImGuiCheckboxFlags(_ label: String?, _ flags: UnsafeMutablePointer<UInt32>!, _ flags_value: UInt32) -> Bool {
	label!.withCString { labelPtr in
		return igCheckboxFlags(labelPtr,flags,flags_value)
	}
}

@inlinable public func ImGuiCloseCurrentPopup() -> Void {
	return igCloseCurrentPopup()
}

@inlinable @discardableResult public func ImGuiCollapsingHeaderBoolPtr(_ label: String?, _ p_open: UnsafeMutablePointer<Bool>!, _ flags: ImGuiTreeNodeFlags) -> Bool {
	label!.withCString { labelPtr in
		return igCollapsingHeaderBoolPtr(labelPtr,p_open,flags)
	}
}

@inlinable @discardableResult public func ImGuiCollapsingHeaderTreeNodeFlags(_ label: String?, _ flags: ImGuiTreeNodeFlags) -> Bool {
	label!.withCString { labelPtr in
		return igCollapsingHeaderTreeNodeFlags(labelPtr,flags)
	}
}

@inlinable @discardableResult public func ImGuiColorButton(_ desc_id: String?, _ col: ImVec4, _ flags: ImGuiColorEditFlags, _ size: ImVec2) -> Bool {
	desc_id!.withCString { desc_idPtr in
		return igColorButton(desc_idPtr,col,flags,size)
	}
}

@inlinable public func ImGuiColorConvertFloat4ToU32(_ `in`: ImVec4) -> ImU32 {
	return igColorConvertFloat4ToU32(`in`)
}

@inlinable public func ImGuiColorConvertHSVtoRGB(_ h: Float, _ s: Float, _ v: Float, _ out_r: inout Float, _ out_g: inout Float, _ out_b: inout Float) -> Void {
	return igColorConvertHSVtoRGB(h,s,v,&out_r,&out_g,&out_b)
}

@inlinable public func ImGuiColorConvertRGBtoHSV(_ r: Float, _ g: Float, _ b: Float, _ out_h: inout Float, _ out_s: inout Float, _ out_v: inout Float) -> Void {
	return igColorConvertRGBtoHSV(r,g,b,&out_h,&out_s,&out_v)
}

@inlinable public func ImGuiColorConvertU32ToFloat4(_ pOut: UnsafeMutablePointer<ImVec4>!, _ `in`: ImU32) -> Void {
	return igColorConvertU32ToFloat4(pOut,`in`)
}

@inlinable @discardableResult public func ImGuiColorEdit3(_ label: String?, _ col: inout SIMD3<Float>, _ flags: ImGuiColorEditFlags) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &col) { colMutPtr in
			colMutPtr.withMemoryRebound(to: Float.self, capacity: 3) { colPtr in
				return igColorEdit3(labelPtr,colPtr,flags)
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiColorEdit4(_ label: String?, _ col: inout SIMD4<Float>, _ flags: ImGuiColorEditFlags) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &col) { colMutPtr in
			colMutPtr.withMemoryRebound(to: Float.self, capacity: 4) { colPtr in
				return igColorEdit4(labelPtr,colPtr,flags)
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiColorPicker3(_ label: String?, _ col: inout SIMD3<Float>, _ flags: ImGuiColorEditFlags) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &col) { colMutPtr in
			colMutPtr.withMemoryRebound(to: Float.self, capacity: 3) { colPtr in
				return igColorPicker3(labelPtr,colPtr,flags)
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiColorPicker4(_ label: String?, _ col: inout SIMD4<Float>, _ flags: ImGuiColorEditFlags, _ ref_col: UnsafePointer<Float>!) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &col) { colMutPtr in
			colMutPtr.withMemoryRebound(to: Float.self, capacity: 4) { colPtr in
				return igColorPicker4(labelPtr,colPtr,flags,ref_col)
			}
		}
	}
}

@inlinable public func ImGuiColumns(_ count: Int32, _ id: String?, _ border: Bool) -> Void {
	id!.withCString { idPtr in
		return igColumns(count,idPtr,border)
	}
}

@inlinable @discardableResult public func ImGuiComboStr(_ label: String?, _ current_item: UnsafeMutablePointer<Int32>!, _ items_separated_by_zeros: String?, _ popup_max_height_in_items: Int32) -> Bool {
	label!.withCString { labelPtr in
		items_separated_by_zeros!.withCString { items_separated_by_zerosPtr in
			return igComboStr(labelPtr,current_item,items_separated_by_zerosPtr,popup_max_height_in_items)
		}
	}
}

@inlinable @discardableResult public func ImGuiComboStrarr(_ label: String?, _ current_item: UnsafeMutablePointer<Int32>!, _ items: [String], _ items_count: Int32, _ popup_max_height_in_items: Int32) -> Bool {
	label!.withCString { labelPtr in
		withArrayOfCStringsBasePointer(items) { itemsPtr in
			return igComboStr_arr(labelPtr,current_item,itemsPtr,items_count,popup_max_height_in_items)
		}
	}
}

@inlinable public func ImGuiCreateContext(_ shared_font_atlas: UnsafeMutablePointer<ImFontAtlas>!) -> ImGuiContext {
	return igCreateContext(shared_font_atlas)
}

@inlinable @discardableResult public func ImGuiDebugCheckVersionAndDataLayout(_ version_str: String?, _ sz_io: Int, _ sz_style: Int, _ sz_vec2: Int, _ sz_vec4: Int, _ sz_drawvert: Int, _ sz_drawidx: Int) -> Bool {
	version_str!.withCString { version_strPtr in
		return igDebugCheckVersionAndDataLayout(version_strPtr,sz_io,sz_style,sz_vec2,sz_vec4,sz_drawvert,sz_drawidx)
	}
}

@inlinable public func ImGuiDestroyContext(_ ctx: ImGuiContext) -> Void {
	return igDestroyContext(ctx)
}

@inlinable @discardableResult public func ImGuiDragFloat(_ label: String?, _ v: UnsafeMutablePointer<Float>!, _ v_speed: Float, _ v_min: Float, _ v_max: Float, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igDragFloat(labelPtr,v,v_speed,v_min,v_max,formatPtr,power)
		}
	}
}

@inlinable @discardableResult public func ImGuiDragFloat2(_ label: String?, _ v: inout SIMD2<Float>, _ v_speed: Float, _ v_min: Float, _ v_max: Float, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Float.self, capacity: 2) { vPtr in
				format!.withCString { formatPtr in
					return igDragFloat2(labelPtr,vPtr,v_speed,v_min,v_max,formatPtr,power)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiDragFloat3(_ label: String?, _ v: inout SIMD3<Float>, _ v_speed: Float, _ v_min: Float, _ v_max: Float, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Float.self, capacity: 3) { vPtr in
				format!.withCString { formatPtr in
					return igDragFloat3(labelPtr,vPtr,v_speed,v_min,v_max,formatPtr,power)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiDragFloat4(_ label: String?, _ v: inout SIMD4<Float>, _ v_speed: Float, _ v_min: Float, _ v_max: Float, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Float.self, capacity: 4) { vPtr in
				format!.withCString { formatPtr in
					return igDragFloat4(labelPtr,vPtr,v_speed,v_min,v_max,formatPtr,power)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiDragFloatRange2(_ label: String?, _ v_current_min: UnsafeMutablePointer<Float>!, _ v_current_max: UnsafeMutablePointer<Float>!, _ v_speed: Float, _ v_min: Float, _ v_max: Float, _ format: String?, _ format_max: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			format_max!.withCString { format_maxPtr in
				return igDragFloatRange2(labelPtr,v_current_min,v_current_max,v_speed,v_min,v_max,formatPtr,format_maxPtr,power)
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiDragInt(_ label: String?, _ v: UnsafeMutablePointer<Int32>!, _ v_speed: Float, _ v_min: Int32, _ v_max: Int32, _ format: String?) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igDragInt(labelPtr,v,v_speed,v_min,v_max,formatPtr)
		}
	}
}

@inlinable @discardableResult public func ImGuiDragInt2(_ label: String?, _ v: inout SIMD2<Int32>, _ v_speed: Float, _ v_min: Int32, _ v_max: Int32, _ format: String?) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Int32.self, capacity: 2) { vPtr in
				format!.withCString { formatPtr in
					return igDragInt2(labelPtr,vPtr,v_speed,v_min,v_max,formatPtr)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiDragInt3(_ label: String?, _ v: inout SIMD3<Int32>, _ v_speed: Float, _ v_min: Int32, _ v_max: Int32, _ format: String?) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Int32.self, capacity: 3) { vPtr in
				format!.withCString { formatPtr in
					return igDragInt3(labelPtr,vPtr,v_speed,v_min,v_max,formatPtr)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiDragInt4(_ label: String?, _ v: inout SIMD4<Int32>, _ v_speed: Float, _ v_min: Int32, _ v_max: Int32, _ format: String?) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Int32.self, capacity: 4) { vPtr in
				format!.withCString { formatPtr in
					return igDragInt4(labelPtr,vPtr,v_speed,v_min,v_max,formatPtr)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiDragIntRange2(_ label: String?, _ v_current_min: UnsafeMutablePointer<Int32>!, _ v_current_max: UnsafeMutablePointer<Int32>!, _ v_speed: Float, _ v_min: Int32, _ v_max: Int32, _ format: String?, _ format_max: String?) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			format_max!.withCString { format_maxPtr in
				return igDragIntRange2(labelPtr,v_current_min,v_current_max,v_speed,v_min,v_max,formatPtr,format_maxPtr)
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiDragScalar(_ label: String?, _ data_type: ImGuiDataType, _ p_data: UnsafeMutableRawPointer!, _ v_speed: Float, _ p_min: UnsafeRawPointer!, _ p_max: UnsafeRawPointer!, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igDragScalar(labelPtr,data_type,p_data,v_speed,p_min,p_max,formatPtr,power)
		}
	}
}

@inlinable @discardableResult public func ImGuiDragScalarN(_ label: String?, _ data_type: ImGuiDataType, _ p_data: UnsafeMutableRawPointer!, _ components: Int32, _ v_speed: Float, _ p_min: UnsafeRawPointer!, _ p_max: UnsafeRawPointer!, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igDragScalarN(labelPtr,data_type,p_data,components,v_speed,p_min,p_max,formatPtr,power)
		}
	}
}

@inlinable public func ImGuiDummy(_ size: ImVec2) -> Void {
	return igDummy(size)
}

@inlinable public func ImGuiEnd() -> Void {
	return igEnd()
}

@inlinable public func ImGuiEndChild() -> Void {
	return igEndChild()
}

@inlinable public func ImGuiEndChildFrame() -> Void {
	return igEndChildFrame()
}

@inlinable public func ImGuiEndCombo() -> Void {
	return igEndCombo()
}

@inlinable public func ImGuiEndDragDropSource() -> Void {
	return igEndDragDropSource()
}

@inlinable public func ImGuiEndDragDropTarget() -> Void {
	return igEndDragDropTarget()
}

@inlinable public func ImGuiEndFrame() -> Void {
	return igEndFrame()
}

@inlinable public func ImGuiEndGroup() -> Void {
	return igEndGroup()
}

@inlinable public func ImGuiEndMainMenuBar() -> Void {
	return igEndMainMenuBar()
}

@inlinable public func ImGuiEndMenu() -> Void {
	return igEndMenu()
}

@inlinable public func ImGuiEndMenuBar() -> Void {
	return igEndMenuBar()
}

@inlinable public func ImGuiEndPopup() -> Void {
	return igEndPopup()
}

@inlinable public func ImGuiEndTabBar() -> Void {
	return igEndTabBar()
}

@inlinable public func ImGuiEndTabItem() -> Void {
	return igEndTabItem()
}

@inlinable public func ImGuiEndTooltip() -> Void {
	return igEndTooltip()
}

@inlinable public func ImGuiGetBackgroundDrawList() -> UnsafeMutablePointer<ImDrawList>! {
	return igGetBackgroundDrawList()
}

@inlinable public func ImGuiGetClipboardText() -> String? {
	return String(cString: igGetClipboardText())
}

@inlinable public func ImGuiGetColorU32Col(_ idx: ImGuiCol, _ alpha_mul: Float) -> ImU32 {
	return igGetColorU32Col(idx,alpha_mul)
}

@inlinable public func ImGuiGetColorU32U32(_ col: ImU32) -> ImU32 {
	return igGetColorU32U32(col)
}

@inlinable public func ImGuiGetColorU32Vec4(_ col: ImVec4) -> ImU32 {
	return igGetColorU32Vec4(col)
}

@inlinable public func ImGuiGetColumnIndex() -> Int32 {
	return igGetColumnIndex()
}

@inlinable public func ImGuiGetColumnOffset(_ column_index: Int32) -> Float {
	return igGetColumnOffset(column_index)
}

@inlinable public func ImGuiGetColumnWidth(_ column_index: Int32) -> Float {
	return igGetColumnWidth(column_index)
}

@inlinable public func ImGuiGetColumnsCount() -> Int32 {
	return igGetColumnsCount()
}

@inlinable public func ImGuiGetContentRegionAvail(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetContentRegionAvail(pOut)
}

@inlinable public func ImGuiGetContentRegionMax(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetContentRegionMax(pOut)
}

@inlinable public func ImGuiGetCurrentContext() -> ImGuiContext {
	return igGetCurrentContext()
}

@inlinable public func ImGuiGetCursorPos(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetCursorPos(pOut)
}

@inlinable public func ImGuiGetCursorPosX() -> Float {
	return igGetCursorPosX()
}

@inlinable public func ImGuiGetCursorPosY() -> Float {
	return igGetCursorPosY()
}

@inlinable public func ImGuiGetCursorScreenPos(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetCursorScreenPos(pOut)
}

@inlinable public func ImGuiGetCursorStartPos(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetCursorStartPos(pOut)
}

@inlinable public func ImGuiGetDragDropPayload() -> UnsafePointer<ImGuiPayload>! {
	return igGetDragDropPayload()
}

@inlinable public func ImGuiGetDrawData() -> UnsafeMutablePointer<ImDrawData>! {
	return igGetDrawData()
}

@inlinable public func ImGuiGetDrawListSharedData() -> ImDrawListSharedData {
	return igGetDrawListSharedData()
}

@inlinable public func ImGuiGetFont() -> UnsafeMutablePointer<ImFont>! {
	return igGetFont()
}

@inlinable public func ImGuiGetFontSize() -> Float {
	return igGetFontSize()
}

@inlinable public func ImGuiGetFontTexUvWhitePixel(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetFontTexUvWhitePixel(pOut)
}

@inlinable public func ImGuiGetForegroundDrawList() -> UnsafeMutablePointer<ImDrawList>! {
	return igGetForegroundDrawList()
}

@inlinable public func ImGuiGetFrameCount() -> Int32 {
	return igGetFrameCount()
}

@inlinable public func ImGuiGetFrameHeight() -> Float {
	return igGetFrameHeight()
}

@inlinable public func ImGuiGetFrameHeightWithSpacing() -> Float {
	return igGetFrameHeightWithSpacing()
}

@inlinable public func ImGuiGetIDPtr(_ ptr_id: UnsafeRawPointer!) -> ImGuiID {
	return igGetIDPtr(ptr_id)
}

@inlinable public func ImGuiGetIDStr(_ str_id: String?) -> ImGuiID {
	str_id!.withCString { str_idPtr in
		return igGetIDStr(str_idPtr)
	}
}

@inlinable public func ImGuiGetIDStrStr(_ str_id_begin: String?, _ str_id_end: String?) -> ImGuiID {
	str_id_begin!.withCString { str_id_beginPtr in
		str_id_end!.withCString { str_id_endPtr in
			return igGetIDStrStr(str_id_beginPtr,str_id_endPtr)
		}
	}
}

@inlinable public func ImGuiGetIO() -> UnsafeMutablePointer<ImGuiIO>! {
	return igGetIO()
}

@inlinable public func ImGuiGetItemRectMax(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetItemRectMax(pOut)
}

@inlinable public func ImGuiGetItemRectMin(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetItemRectMin(pOut)
}

@inlinable public func ImGuiGetItemRectSize(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetItemRectSize(pOut)
}

@inlinable public func ImGuiGetKeyIndex(_ imgui_key: ImGuiKey) -> Int32 {
	return igGetKeyIndex(imgui_key)
}

@inlinable public func ImGuiGetKeyPressedAmount(_ key_index: Int32, _ repeat_delay: Float, _ rate: Float) -> Int32 {
	return igGetKeyPressedAmount(key_index,repeat_delay,rate)
}

@inlinable public func ImGuiGetMouseCursor() -> ImGuiMouseCursor {
	return igGetMouseCursor()
}

@inlinable public func ImGuiGetMouseDragDelta(_ pOut: UnsafeMutablePointer<ImVec2>!, _ button: ImGuiMouseButton, _ lock_threshold: Float) -> Void {
	return igGetMouseDragDelta(pOut,button,lock_threshold)
}

@inlinable public func ImGuiGetMousePos(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetMousePos(pOut)
}

@inlinable public func ImGuiGetMousePosOnOpeningCurrentPopup(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetMousePosOnOpeningCurrentPopup(pOut)
}

@inlinable public func ImGuiGetScrollMaxX() -> Float {
	return igGetScrollMaxX()
}

@inlinable public func ImGuiGetScrollMaxY() -> Float {
	return igGetScrollMaxY()
}

@inlinable public func ImGuiGetScrollX() -> Float {
	return igGetScrollX()
}

@inlinable public func ImGuiGetScrollY() -> Float {
	return igGetScrollY()
}

@inlinable public func ImGuiGetStateStorage() -> UnsafeMutablePointer<ImGuiStorage>! {
	return igGetStateStorage()
}

@inlinable public func ImGuiGetStyle() -> UnsafeMutablePointer<ImGuiStyle>! {
	return igGetStyle()
}

@inlinable public func ImGuiGetStyleColorName(_ idx: ImGuiCol) -> String? {
	return String(cString: igGetStyleColorName(idx))
}

@inlinable public func ImGuiGetStyleColorVec4(_ idx: ImGuiCol) -> UnsafePointer<ImVec4>! {
	return igGetStyleColorVec4(idx)
}

@inlinable public func ImGuiGetTextLineHeight() -> Float {
	return igGetTextLineHeight()
}

@inlinable public func ImGuiGetTextLineHeightWithSpacing() -> Float {
	return igGetTextLineHeightWithSpacing()
}

@inlinable public func ImGuiGetTime() -> Double {
	return igGetTime()
}

@inlinable public func ImGuiGetTreeNodeToLabelSpacing() -> Float {
	return igGetTreeNodeToLabelSpacing()
}

@inlinable public func ImGuiGetVersion() -> String? {
	return String(cString: igGetVersion())
}

@inlinable public func ImGuiGetWindowContentRegionMax(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetWindowContentRegionMax(pOut)
}

@inlinable public func ImGuiGetWindowContentRegionMin(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetWindowContentRegionMin(pOut)
}

@inlinable public func ImGuiGetWindowContentRegionWidth() -> Float {
	return igGetWindowContentRegionWidth()
}

@inlinable public func ImGuiGetWindowDrawList() -> UnsafeMutablePointer<ImDrawList>! {
	return igGetWindowDrawList()
}

@inlinable public func ImGuiGetWindowHeight() -> Float {
	return igGetWindowHeight()
}

@inlinable public func ImGuiGetWindowPos(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetWindowPos(pOut)
}

@inlinable public func ImGuiGetWindowSize(_ pOut: UnsafeMutablePointer<ImVec2>!) -> Void {
	return igGetWindowSize(pOut)
}

@inlinable public func ImGuiGetWindowWidth() -> Float {
	return igGetWindowWidth()
}

@inlinable public func ImGuiIOAddInputCharacter(_ this: UnsafeMutablePointer<ImGuiIO>!, _ c: UInt32) -> Void {
	return ImGuiIO_AddInputCharacter(this,c)
}

@inlinable public func ImGuiIOAddInputCharacterUTF16(_ this: UnsafeMutablePointer<ImGuiIO>!, _ c: ImWchar16) -> Void {
	return ImGuiIO_AddInputCharacterUTF16(this,c)
}

@inlinable public func ImGuiIOAddInputCharactersUTF8(_ this: UnsafeMutablePointer<ImGuiIO>!, _ str: String?) -> Void {
	str!.withCString { strPtr in
		return ImGuiIO_AddInputCharactersUTF8(this,strPtr)
	}
}

@inlinable public func ImGuiIOClearInputCharacters(_ this: UnsafeMutablePointer<ImGuiIO>!) -> Void {
	return ImGuiIO_ClearInputCharacters(this)
}

@inlinable public func ImGuiImage(_ user_texture_id: ImTextureID, _ size: ImVec2, _ uv0: ImVec2, _ uv1: ImVec2, _ tint_col: ImVec4, _ border_col: ImVec4) -> Void {
	return igImage(user_texture_id,size,uv0,uv1,tint_col,border_col)
}

@inlinable @discardableResult public func ImGuiImageButton(_ user_texture_id: ImTextureID, _ size: ImVec2, _ uv0: ImVec2, _ uv1: ImVec2, _ frame_padding: Int32, _ bg_col: ImVec4, _ tint_col: ImVec4) -> Bool {
	return igImageButton(user_texture_id,size,uv0,uv1,frame_padding,bg_col,tint_col)
}

@inlinable public func ImGuiIndent(_ indent_w: Float) -> Void {
	return igIndent(indent_w)
}

@inlinable @discardableResult public func ImGuiInputDouble(_ label: String?, _ v: UnsafeMutablePointer<Double>!, _ step: Double, _ step_fast: Double, _ format: String?, _ flags: ImGuiInputTextFlags) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igInputDouble(labelPtr,v,step,step_fast,formatPtr,flags)
		}
	}
}

@inlinable @discardableResult public func ImGuiInputFloat(_ label: String?, _ v: UnsafeMutablePointer<Float>!, _ step: Float, _ step_fast: Float, _ format: String?, _ flags: ImGuiInputTextFlags) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igInputFloat(labelPtr,v,step,step_fast,formatPtr,flags)
		}
	}
}

@inlinable @discardableResult public func ImGuiInputFloat2(_ label: String?, _ v: inout SIMD2<Float>, _ format: String?, _ flags: ImGuiInputTextFlags) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Float.self, capacity: 2) { vPtr in
				format!.withCString { formatPtr in
					return igInputFloat2(labelPtr,vPtr,formatPtr,flags)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiInputFloat3(_ label: String?, _ v: inout SIMD3<Float>, _ format: String?, _ flags: ImGuiInputTextFlags) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Float.self, capacity: 3) { vPtr in
				format!.withCString { formatPtr in
					return igInputFloat3(labelPtr,vPtr,formatPtr,flags)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiInputFloat4(_ label: String?, _ v: inout SIMD4<Float>, _ format: String?, _ flags: ImGuiInputTextFlags) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Float.self, capacity: 4) { vPtr in
				format!.withCString { formatPtr in
					return igInputFloat4(labelPtr,vPtr,formatPtr,flags)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiInputInt(_ label: String?, _ v: UnsafeMutablePointer<Int32>!, _ step: Int32, _ step_fast: Int32, _ flags: ImGuiInputTextFlags) -> Bool {
	label!.withCString { labelPtr in
		return igInputInt(labelPtr,v,step,step_fast,flags)
	}
}

@inlinable @discardableResult public func ImGuiInputInt2(_ label: String?, _ v: inout SIMD2<Int32>, _ flags: ImGuiInputTextFlags) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Int32.self, capacity: 2) { vPtr in
				return igInputInt2(labelPtr,vPtr,flags)
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiInputInt3(_ label: String?, _ v: inout SIMD3<Int32>, _ flags: ImGuiInputTextFlags) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Int32.self, capacity: 3) { vPtr in
				return igInputInt3(labelPtr,vPtr,flags)
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiInputInt4(_ label: String?, _ v: inout SIMD4<Int32>, _ flags: ImGuiInputTextFlags) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Int32.self, capacity: 4) { vPtr in
				return igInputInt4(labelPtr,vPtr,flags)
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiInputScalar(_ label: String?, _ data_type: ImGuiDataType, _ p_data: UnsafeMutableRawPointer!, _ p_step: UnsafeRawPointer!, _ p_step_fast: UnsafeRawPointer!, _ format: String?, _ flags: ImGuiInputTextFlags) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igInputScalar(labelPtr,data_type,p_data,p_step,p_step_fast,formatPtr,flags)
		}
	}
}

@inlinable @discardableResult public func ImGuiInputScalarN(_ label: String?, _ data_type: ImGuiDataType, _ p_data: UnsafeMutableRawPointer!, _ components: Int32, _ p_step: UnsafeRawPointer!, _ p_step_fast: UnsafeRawPointer!, _ format: String?, _ flags: ImGuiInputTextFlags) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igInputScalarN(labelPtr,data_type,p_data,components,p_step,p_step_fast,formatPtr,flags)
		}
	}
}

@inlinable @discardableResult public func ImGuiInputText(_ label: String?, _ buf: inout String?, _ buf_size: Int, _ flags: ImGuiInputTextFlags, _ callback: @escaping ImGuiInputTextCallback, _ user_data: UnsafeMutableRawPointer!) -> Bool {
	label!.withCString { labelPtr in
		buf!.withCString { bufPtr in
			return igInputText(labelPtr,UnsafeMutablePointer(mutating: bufPtr),buf_size,flags,callback,user_data)
		}
	}
}

@inlinable public func ImGuiInputTextCallbackDataDeleteChars(_ this: UnsafeMutablePointer<ImGuiInputTextCallbackData>!, _ pos: Int32, _ bytes_count: Int32) -> Void {
	return ImGuiInputTextCallbackData_DeleteChars(this,pos,bytes_count)
}

@inlinable @discardableResult public func ImGuiInputTextCallbackDataHasSelection(_ this: UnsafeMutablePointer<ImGuiInputTextCallbackData>!) -> Bool {
	return ImGuiInputTextCallbackData_HasSelection(this)
}

@inlinable public func ImGuiInputTextCallbackDataInsertChars(_ this: UnsafeMutablePointer<ImGuiInputTextCallbackData>!, _ pos: Int32, _ text: String?, _ text_end: String?) -> Void {
	text!.withCString { textPtr in
		text_end!.withCString { text_endPtr in
			return ImGuiInputTextCallbackData_InsertChars(this,pos,textPtr,text_endPtr)
		}
	}
}

@inlinable @discardableResult public func ImGuiInputTextMultiline(_ label: String?, _ buf: inout String?, _ buf_size: Int, _ size: ImVec2, _ flags: ImGuiInputTextFlags, _ callback: @escaping ImGuiInputTextCallback, _ user_data: UnsafeMutableRawPointer!) -> Bool {
	label!.withCString { labelPtr in
		buf!.withCString { bufPtr in
			return igInputTextMultiline(labelPtr,UnsafeMutablePointer(mutating: bufPtr),buf_size,size,flags,callback,user_data)
		}
	}
}

@inlinable @discardableResult public func ImGuiInputTextWithHint(_ label: String?, _ hint: String?, _ buf: inout String?, _ buf_size: Int, _ flags: ImGuiInputTextFlags, _ callback: @escaping ImGuiInputTextCallback, _ user_data: UnsafeMutableRawPointer!) -> Bool {
	label!.withCString { labelPtr in
		hint!.withCString { hintPtr in
			buf!.withCString { bufPtr in
				return igInputTextWithHint(labelPtr,hintPtr,UnsafeMutablePointer(mutating: bufPtr),buf_size,flags,callback,user_data)
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiInvisibleButton(_ str_id: String?, _ size: ImVec2) -> Bool {
	str_id!.withCString { str_idPtr in
		return igInvisibleButton(str_idPtr,size)
	}
}

@inlinable @discardableResult public func ImGuiIsAnyItemActive() -> Bool {
	return igIsAnyItemActive()
}

@inlinable @discardableResult public func ImGuiIsAnyItemFocused() -> Bool {
	return igIsAnyItemFocused()
}

@inlinable @discardableResult public func ImGuiIsAnyItemHovered() -> Bool {
	return igIsAnyItemHovered()
}

@inlinable @discardableResult public func ImGuiIsAnyMouseDown() -> Bool {
	return igIsAnyMouseDown()
}

@inlinable @discardableResult public func ImGuiIsItemActivated() -> Bool {
	return igIsItemActivated()
}

@inlinable @discardableResult public func ImGuiIsItemActive() -> Bool {
	return igIsItemActive()
}

@inlinable @discardableResult public func ImGuiIsItemClicked(_ mouse_button: ImGuiMouseButton) -> Bool {
	return igIsItemClicked(mouse_button)
}

@inlinable @discardableResult public func ImGuiIsItemDeactivated() -> Bool {
	return igIsItemDeactivated()
}

@inlinable @discardableResult public func ImGuiIsItemDeactivatedAfterEdit() -> Bool {
	return igIsItemDeactivatedAfterEdit()
}

@inlinable @discardableResult public func ImGuiIsItemEdited() -> Bool {
	return igIsItemEdited()
}

@inlinable @discardableResult public func ImGuiIsItemFocused() -> Bool {
	return igIsItemFocused()
}

@inlinable @discardableResult public func ImGuiIsItemHovered(_ flags: ImGuiHoveredFlags) -> Bool {
	return igIsItemHovered(flags)
}

@inlinable @discardableResult public func ImGuiIsItemToggledOpen() -> Bool {
	return igIsItemToggledOpen()
}

@inlinable @discardableResult public func ImGuiIsItemVisible() -> Bool {
	return igIsItemVisible()
}

@inlinable @discardableResult public func ImGuiIsKeyDown(_ user_key_index: Int32) -> Bool {
	return igIsKeyDown(user_key_index)
}

@inlinable @discardableResult public func ImGuiIsKeyPressed(_ user_key_index: Int32, _ `repeat`: Bool) -> Bool {
	return igIsKeyPressed(user_key_index,`repeat`)
}

@inlinable @discardableResult public func ImGuiIsKeyReleased(_ user_key_index: Int32) -> Bool {
	return igIsKeyReleased(user_key_index)
}

@inlinable @discardableResult public func ImGuiIsMouseClicked(_ button: ImGuiMouseButton, _ `repeat`: Bool) -> Bool {
	return igIsMouseClicked(button,`repeat`)
}

@inlinable @discardableResult public func ImGuiIsMouseDoubleClicked(_ button: ImGuiMouseButton) -> Bool {
	return igIsMouseDoubleClicked(button)
}

@inlinable @discardableResult public func ImGuiIsMouseDown(_ button: ImGuiMouseButton) -> Bool {
	return igIsMouseDown(button)
}

@inlinable @discardableResult public func ImGuiIsMouseDragging(_ button: ImGuiMouseButton, _ lock_threshold: Float) -> Bool {
	return igIsMouseDragging(button,lock_threshold)
}

@inlinable @discardableResult public func ImGuiIsMouseHoveringRect(_ r_min: ImVec2, _ r_max: ImVec2, _ clip: Bool) -> Bool {
	return igIsMouseHoveringRect(r_min,r_max,clip)
}

@inlinable @discardableResult public func ImGuiIsMousePosValid(_ mouse_pos: UnsafePointer<ImVec2>!) -> Bool {
	return igIsMousePosValid(mouse_pos)
}

@inlinable @discardableResult public func ImGuiIsMouseReleased(_ button: ImGuiMouseButton) -> Bool {
	return igIsMouseReleased(button)
}

@inlinable @discardableResult public func ImGuiIsPopupOpen(_ str_id: String?) -> Bool {
	str_id!.withCString { str_idPtr in
		return igIsPopupOpen(str_idPtr)
	}
}

@inlinable @discardableResult public func ImGuiIsRectVisibleNil(_ size: ImVec2) -> Bool {
	return igIsRectVisibleNil(size)
}

@inlinable @discardableResult public func ImGuiIsRectVisibleVec2(_ rect_min: ImVec2, _ rect_max: ImVec2) -> Bool {
	return igIsRectVisibleVec2(rect_min,rect_max)
}

@inlinable @discardableResult public func ImGuiIsWindowAppearing() -> Bool {
	return igIsWindowAppearing()
}

@inlinable @discardableResult public func ImGuiIsWindowCollapsed() -> Bool {
	return igIsWindowCollapsed()
}

@inlinable @discardableResult public func ImGuiIsWindowFocused(_ flags: ImGuiFocusedFlags) -> Bool {
	return igIsWindowFocused(flags)
}

@inlinable @discardableResult public func ImGuiIsWindowHovered(_ flags: ImGuiHoveredFlags) -> Bool {
	return igIsWindowHovered(flags)
}

@inlinable public func ImGuiLabelTextV(_ label: String?, _ fmt: String?, _ args: CVarArg...) -> Void {
	label!.withCString { labelPtr in
		fmt!.withCString { fmtPtr in
			withVaList(args) { varArgsPtr in
				return igLabelTextV(labelPtr,fmtPtr,varArgsPtr)
			}
		}
	}
}

@inlinable public func ImGuiListBoxFooter() -> Void {
	return igListBoxFooter()
}

@inlinable @discardableResult public func ImGuiListBoxHeaderInt(_ label: String?, _ items_count: Int32, _ height_in_items: Int32) -> Bool {
	label!.withCString { labelPtr in
		return igListBoxHeaderInt(labelPtr,items_count,height_in_items)
	}
}

@inlinable @discardableResult public func ImGuiListBoxHeaderVec2(_ label: String?, _ size: ImVec2) -> Bool {
	label!.withCString { labelPtr in
		return igListBoxHeaderVec2(labelPtr,size)
	}
}

@inlinable @discardableResult public func ImGuiListBoxStrarr(_ label: String?, _ current_item: UnsafeMutablePointer<Int32>!, _ items: [String], _ items_count: Int32, _ height_in_items: Int32) -> Bool {
	label!.withCString { labelPtr in
		withArrayOfCStringsBasePointer(items) { itemsPtr in
			return igListBoxStr_arr(labelPtr,current_item,itemsPtr,items_count,height_in_items)
		}
	}
}

@inlinable public func ImGuiListClipperBegin(_ this: UnsafeMutablePointer<ImGuiListClipper>!, _ items_count: Int32, _ items_height: Float) -> Void {
	return ImGuiListClipper_Begin(this,items_count,items_height)
}

@inlinable public func ImGuiListClipperEnd(_ this: UnsafeMutablePointer<ImGuiListClipper>!) -> Void {
	return ImGuiListClipper_End(this)
}

@inlinable @discardableResult public func ImGuiListClipperStep(_ this: UnsafeMutablePointer<ImGuiListClipper>!) -> Bool {
	return ImGuiListClipper_Step(this)
}

@inlinable public func ImGuiLoadIniSettingsFromDisk(_ ini_filename: String?) -> Void {
	ini_filename!.withCString { ini_filenamePtr in
		return igLoadIniSettingsFromDisk(ini_filenamePtr)
	}
}

@inlinable public func ImGuiLoadIniSettingsFromMemory(_ ini_data: String?, _ ini_size: Int) -> Void {
	ini_data!.withCString { ini_dataPtr in
		return igLoadIniSettingsFromMemory(ini_dataPtr,ini_size)
	}
}

@inlinable public func ImGuiLogButtons() -> Void {
	return igLogButtons()
}

@inlinable public func ImGuiLogFinish() -> Void {
	return igLogFinish()
}

@inlinable public func ImGuiLogToClipboard(_ auto_open_depth: Int32) -> Void {
	return igLogToClipboard(auto_open_depth)
}

@inlinable public func ImGuiLogToFile(_ auto_open_depth: Int32, _ filename: String?) -> Void {
	filename!.withCString { filenamePtr in
		return igLogToFile(auto_open_depth,filenamePtr)
	}
}

@inlinable public func ImGuiLogToTTY(_ auto_open_depth: Int32) -> Void {
	return igLogToTTY(auto_open_depth)
}

@inlinable public func ImGuiMemAlloc(_ size: Int) -> UnsafeMutableRawPointer! {
	return igMemAlloc(size)
}

@inlinable public func ImGuiMemFree(_ ptr: UnsafeMutableRawPointer!) -> Void {
	return igMemFree(ptr)
}

@inlinable @discardableResult public func ImGuiMenuItemBool(_ label: String?, _ shortcut: String?, _ selected: Bool, _ enabled: Bool) -> Bool {
	label!.withCString { labelPtr in
		shortcut!.withCString { shortcutPtr in
			return igMenuItemBool(labelPtr,shortcutPtr,selected,enabled)
		}
	}
}

@inlinable @discardableResult public func ImGuiMenuItemBoolPtr(_ label: String?, _ shortcut: String?, _ p_selected: UnsafeMutablePointer<Bool>!, _ enabled: Bool) -> Bool {
	label!.withCString { labelPtr in
		shortcut!.withCString { shortcutPtr in
			return igMenuItemBoolPtr(labelPtr,shortcutPtr,p_selected,enabled)
		}
	}
}

@inlinable public func ImGuiNewFrame() -> Void {
	return igNewFrame()
}

@inlinable public func ImGuiNewLine() -> Void {
	return igNewLine()
}

@inlinable public func ImGuiNextColumn() -> Void {
	return igNextColumn()
}

@inlinable public func ImGuiOpenPopup(_ str_id: String?) -> Void {
	str_id!.withCString { str_idPtr in
		return igOpenPopup(str_idPtr)
	}
}

@inlinable @discardableResult public func ImGuiOpenPopupOnItemClick(_ str_id: String?, _ mouse_button: ImGuiMouseButton) -> Bool {
	str_id!.withCString { str_idPtr in
		return igOpenPopupOnItemClick(str_idPtr,mouse_button)
	}
}

@inlinable public func ImGuiPayloadClear(_ this: UnsafeMutablePointer<ImGuiPayload>!) -> Void {
	return ImGuiPayload_Clear(this)
}

@inlinable @discardableResult public func ImGuiPayloadIsDataType(_ this: UnsafeMutablePointer<ImGuiPayload>!, _ type: String?) -> Bool {
	type!.withCString { typePtr in
		return ImGuiPayload_IsDataType(this,typePtr)
	}
}

@inlinable @discardableResult public func ImGuiPayloadIsDelivery(_ this: UnsafeMutablePointer<ImGuiPayload>!) -> Bool {
	return ImGuiPayload_IsDelivery(this)
}

@inlinable @discardableResult public func ImGuiPayloadIsPreview(_ this: UnsafeMutablePointer<ImGuiPayload>!) -> Bool {
	return ImGuiPayload_IsPreview(this)
}

@inlinable public func ImGuiPlotHistogramFloatPtr(_ label: String?, _ values: UnsafePointer<Float>!, _ values_count: Int32, _ values_offset: Int32, _ overlay_text: String?, _ scale_min: Float, _ scale_max: Float, _ graph_size: ImVec2, _ stride: Int32) -> Void {
	label!.withCString { labelPtr in
		overlay_text!.withCString { overlay_textPtr in
			return igPlotHistogramFloatPtr(labelPtr,values,values_count,values_offset,overlay_textPtr,scale_min,scale_max,graph_size,stride)
		}
	}
}

@inlinable public func ImGuiPlotLinesFloatPtr(_ label: String?, _ values: UnsafePointer<Float>!, _ values_count: Int32, _ values_offset: Int32, _ overlay_text: String?, _ scale_min: Float, _ scale_max: Float, _ graph_size: ImVec2, _ stride: Int32) -> Void {
	label!.withCString { labelPtr in
		overlay_text!.withCString { overlay_textPtr in
			return igPlotLinesFloatPtr(labelPtr,values,values_count,values_offset,overlay_textPtr,scale_min,scale_max,graph_size,stride)
		}
	}
}

@inlinable public func ImGuiPopAllowKeyboardFocus() -> Void {
	return igPopAllowKeyboardFocus()
}

@inlinable public func ImGuiPopButtonRepeat() -> Void {
	return igPopButtonRepeat()
}

@inlinable public func ImGuiPopClipRect() -> Void {
	return igPopClipRect()
}

@inlinable public func ImGuiPopFont() -> Void {
	return igPopFont()
}

@inlinable public func ImGuiPopID() -> Void {
	return igPopID()
}

@inlinable public func ImGuiPopItemWidth() -> Void {
	return igPopItemWidth()
}

@inlinable public func ImGuiPopStyleColor(_ count: Int32) -> Void {
	return igPopStyleColor(count)
}

@inlinable public func ImGuiPopStyleVar(_ count: Int32) -> Void {
	return igPopStyleVar(count)
}

@inlinable public func ImGuiPopTextWrapPos() -> Void {
	return igPopTextWrapPos()
}

@inlinable public func ImGuiProgressBar(_ fraction: Float, _ size_arg: ImVec2, _ overlay: String?) -> Void {
	overlay!.withCString { overlayPtr in
		return igProgressBar(fraction,size_arg,overlayPtr)
	}
}

@inlinable public func ImGuiPushAllowKeyboardFocus(_ allow_keyboard_focus: Bool) -> Void {
	return igPushAllowKeyboardFocus(allow_keyboard_focus)
}

@inlinable public func ImGuiPushButtonRepeat(_ `repeat`: Bool) -> Void {
	return igPushButtonRepeat(`repeat`)
}

@inlinable public func ImGuiPushClipRect(_ clip_rect_min: ImVec2, _ clip_rect_max: ImVec2, _ intersect_with_current_clip_rect: Bool) -> Void {
	return igPushClipRect(clip_rect_min,clip_rect_max,intersect_with_current_clip_rect)
}

@inlinable public func ImGuiPushFont(_ font: UnsafeMutablePointer<ImFont>!) -> Void {
	return igPushFont(font)
}

@inlinable public func ImGuiPushIDInt(_ int_id: Int32) -> Void {
	return igPushIDInt(int_id)
}

@inlinable public func ImGuiPushIDPtr(_ ptr_id: UnsafeRawPointer!) -> Void {
	return igPushIDPtr(ptr_id)
}

@inlinable public func ImGuiPushIDStr(_ str_id: String?) -> Void {
	str_id!.withCString { str_idPtr in
		return igPushIDStr(str_idPtr)
	}
}

@inlinable public func ImGuiPushIDStrStr(_ str_id_begin: String?, _ str_id_end: String?) -> Void {
	str_id_begin!.withCString { str_id_beginPtr in
		str_id_end!.withCString { str_id_endPtr in
			return igPushIDStrStr(str_id_beginPtr,str_id_endPtr)
		}
	}
}

@inlinable public func ImGuiPushItemWidth(_ item_width: Float) -> Void {
	return igPushItemWidth(item_width)
}

@inlinable public func ImGuiPushStyleColorU32(_ idx: ImGuiCol, _ col: ImU32) -> Void {
	return igPushStyleColorU32(idx,col)
}

@inlinable public func ImGuiPushStyleColorVec4(_ idx: ImGuiCol, _ col: ImVec4) -> Void {
	return igPushStyleColorVec4(idx,col)
}

@inlinable public func ImGuiPushStyleVarFloat(_ idx: ImGuiStyleVar, _ val: Float) -> Void {
	return igPushStyleVarFloat(idx,val)
}

@inlinable public func ImGuiPushStyleVarVec2(_ idx: ImGuiStyleVar, _ val: ImVec2) -> Void {
	return igPushStyleVarVec2(idx,val)
}

@inlinable public func ImGuiPushTextWrapPos(_ wrap_local_pos_x: Float) -> Void {
	return igPushTextWrapPos(wrap_local_pos_x)
}

@inlinable @discardableResult public func ImGuiRadioButtonBool(_ label: String?, _ active: Bool) -> Bool {
	label!.withCString { labelPtr in
		return igRadioButtonBool(labelPtr,active)
	}
}

@inlinable @discardableResult public func ImGuiRadioButtonIntPtr(_ label: String?, _ v: UnsafeMutablePointer<Int32>!, _ v_button: Int32) -> Bool {
	label!.withCString { labelPtr in
		return igRadioButtonIntPtr(labelPtr,v,v_button)
	}
}

@inlinable public func ImGuiRender() -> Void {
	return igRender()
}

@inlinable public func ImGuiResetMouseDragDelta(_ button: ImGuiMouseButton) -> Void {
	return igResetMouseDragDelta(button)
}

@inlinable public func ImGuiSameLine(_ offset_from_start_x: Float, _ spacing: Float) -> Void {
	return igSameLine(offset_from_start_x,spacing)
}

@inlinable public func ImGuiSaveIniSettingsToDisk(_ ini_filename: String?) -> Void {
	ini_filename!.withCString { ini_filenamePtr in
		return igSaveIniSettingsToDisk(ini_filenamePtr)
	}
}

@inlinable public func ImGuiSaveIniSettingsToMemory(_ out_ini_size: UnsafeMutablePointer<Int>!) -> String? {
	return String(cString: igSaveIniSettingsToMemory(out_ini_size))
}

@inlinable @discardableResult public func ImGuiSelectableBool(_ label: String?, _ selected: Bool, _ flags: ImGuiSelectableFlags, _ size: ImVec2) -> Bool {
	label!.withCString { labelPtr in
		return igSelectableBool(labelPtr,selected,flags,size)
	}
}

@inlinable @discardableResult public func ImGuiSelectableBoolPtr(_ label: String?, _ p_selected: UnsafeMutablePointer<Bool>!, _ flags: ImGuiSelectableFlags, _ size: ImVec2) -> Bool {
	label!.withCString { labelPtr in
		return igSelectableBoolPtr(labelPtr,p_selected,flags,size)
	}
}

@inlinable public func ImGuiSeparator() -> Void {
	return igSeparator()
}

@inlinable public func ImGuiSetClipboardText(_ text: String?) -> Void {
	text!.withCString { textPtr in
		return igSetClipboardText(textPtr)
	}
}

@inlinable public func ImGuiSetColorEditOptions(_ flags: ImGuiColorEditFlags) -> Void {
	return igSetColorEditOptions(flags)
}

@inlinable public func ImGuiSetColumnOffset(_ column_index: Int32, _ offset_x: Float) -> Void {
	return igSetColumnOffset(column_index,offset_x)
}

@inlinable public func ImGuiSetColumnWidth(_ column_index: Int32, _ width: Float) -> Void {
	return igSetColumnWidth(column_index,width)
}

@inlinable public func ImGuiSetCurrentContext(_ ctx: ImGuiContext) -> Void {
	return igSetCurrentContext(ctx)
}

@inlinable public func ImGuiSetCursorPos(_ local_pos: ImVec2) -> Void {
	return igSetCursorPos(local_pos)
}

@inlinable public func ImGuiSetCursorPosX(_ local_x: Float) -> Void {
	return igSetCursorPosX(local_x)
}

@inlinable public func ImGuiSetCursorPosY(_ local_y: Float) -> Void {
	return igSetCursorPosY(local_y)
}

@inlinable public func ImGuiSetCursorScreenPos(_ pos: ImVec2) -> Void {
	return igSetCursorScreenPos(pos)
}

@inlinable @discardableResult public func ImGuiSetDragDropPayload(_ type: String?, _ data: UnsafeRawPointer!, _ sz: Int, _ cond: ImGuiCond) -> Bool {
	type!.withCString { typePtr in
		return igSetDragDropPayload(typePtr,data,sz,cond)
	}
}

@inlinable public func ImGuiSetItemAllowOverlap() -> Void {
	return igSetItemAllowOverlap()
}

@inlinable public func ImGuiSetItemDefaultFocus() -> Void {
	return igSetItemDefaultFocus()
}

@inlinable public func ImGuiSetKeyboardFocusHere(_ offset: Int32) -> Void {
	return igSetKeyboardFocusHere(offset)
}

@inlinable public func ImGuiSetMouseCursor(_ cursor_type: ImGuiMouseCursor) -> Void {
	return igSetMouseCursor(cursor_type)
}

@inlinable public func ImGuiSetNextItemOpen(_ is_open: Bool, _ cond: ImGuiCond) -> Void {
	return igSetNextItemOpen(is_open,cond)
}

@inlinable public func ImGuiSetNextItemWidth(_ item_width: Float) -> Void {
	return igSetNextItemWidth(item_width)
}

@inlinable public func ImGuiSetNextWindowBgAlpha(_ alpha: Float) -> Void {
	return igSetNextWindowBgAlpha(alpha)
}

@inlinable public func ImGuiSetNextWindowCollapsed(_ collapsed: Bool, _ cond: ImGuiCond) -> Void {
	return igSetNextWindowCollapsed(collapsed,cond)
}

@inlinable public func ImGuiSetNextWindowContentSize(_ size: ImVec2) -> Void {
	return igSetNextWindowContentSize(size)
}

@inlinable public func ImGuiSetNextWindowFocus() -> Void {
	return igSetNextWindowFocus()
}

@inlinable public func ImGuiSetNextWindowPos(_ pos: ImVec2, _ cond: ImGuiCond, _ pivot: ImVec2) -> Void {
	return igSetNextWindowPos(pos,cond,pivot)
}

@inlinable public func ImGuiSetNextWindowSize(_ size: ImVec2, _ cond: ImGuiCond) -> Void {
	return igSetNextWindowSize(size,cond)
}

@inlinable public func ImGuiSetNextWindowSizeConstraints(_ size_min: ImVec2, _ size_max: ImVec2, _ custom_callback: @escaping ImGuiSizeCallback, _ custom_callback_data: UnsafeMutableRawPointer!) -> Void {
	return igSetNextWindowSizeConstraints(size_min,size_max,custom_callback,custom_callback_data)
}

@inlinable public func ImGuiSetScrollFromPosX(_ local_x: Float, _ center_x_ratio: Float) -> Void {
	return igSetScrollFromPosX(local_x,center_x_ratio)
}

@inlinable public func ImGuiSetScrollFromPosY(_ local_y: Float, _ center_y_ratio: Float) -> Void {
	return igSetScrollFromPosY(local_y,center_y_ratio)
}

@inlinable public func ImGuiSetScrollHereX(_ center_x_ratio: Float) -> Void {
	return igSetScrollHereX(center_x_ratio)
}

@inlinable public func ImGuiSetScrollHereY(_ center_y_ratio: Float) -> Void {
	return igSetScrollHereY(center_y_ratio)
}

@inlinable public func ImGuiSetScrollX(_ scroll_x: Float) -> Void {
	return igSetScrollX(scroll_x)
}

@inlinable public func ImGuiSetScrollY(_ scroll_y: Float) -> Void {
	return igSetScrollY(scroll_y)
}

@inlinable public func ImGuiSetStateStorage(_ storage: UnsafeMutablePointer<ImGuiStorage>!) -> Void {
	return igSetStateStorage(storage)
}

@inlinable public func ImGuiSetTabItemClosed(_ tab_or_docked_window_label: String?) -> Void {
	tab_or_docked_window_label!.withCString { tab_or_docked_window_labelPtr in
		return igSetTabItemClosed(tab_or_docked_window_labelPtr)
	}
}

@inlinable public func ImGuiSetTooltipV(_ fmt: String?, _ args: CVarArg...) -> Void {
	fmt!.withCString { fmtPtr in
		withVaList(args) { varArgsPtr in
			return igSetTooltipV(fmtPtr,varArgsPtr)
		}
	}
}

@inlinable public func ImGuiSetWindowCollapsedBool(_ collapsed: Bool, _ cond: ImGuiCond) -> Void {
	return igSetWindowCollapsedBool(collapsed,cond)
}

@inlinable public func ImGuiSetWindowCollapsedStr(_ name: String?, _ collapsed: Bool, _ cond: ImGuiCond) -> Void {
	name!.withCString { namePtr in
		return igSetWindowCollapsedStr(namePtr,collapsed,cond)
	}
}

@inlinable public func ImGuiSetWindowFocusNil() -> Void {
	return igSetWindowFocusNil()
}

@inlinable public func ImGuiSetWindowFocusStr(_ name: String?) -> Void {
	name!.withCString { namePtr in
		return igSetWindowFocusStr(namePtr)
	}
}

@inlinable public func ImGuiSetWindowFontScale(_ scale: Float) -> Void {
	return igSetWindowFontScale(scale)
}

@inlinable public func ImGuiSetWindowPosStr(_ name: String?, _ pos: ImVec2, _ cond: ImGuiCond) -> Void {
	name!.withCString { namePtr in
		return igSetWindowPosStr(namePtr,pos,cond)
	}
}

@inlinable public func ImGuiSetWindowPosVec2(_ pos: ImVec2, _ cond: ImGuiCond) -> Void {
	return igSetWindowPosVec2(pos,cond)
}

@inlinable public func ImGuiSetWindowSizeStr(_ name: String?, _ size: ImVec2, _ cond: ImGuiCond) -> Void {
	name!.withCString { namePtr in
		return igSetWindowSizeStr(namePtr,size,cond)
	}
}

@inlinable public func ImGuiSetWindowSizeVec2(_ size: ImVec2, _ cond: ImGuiCond) -> Void {
	return igSetWindowSizeVec2(size,cond)
}

@inlinable public func ImGuiShowAboutWindow(_ p_open: UnsafeMutablePointer<Bool>!) -> Void {
	return igShowAboutWindow(p_open)
}

@inlinable public func ImGuiShowDemoWindow(_ p_open: UnsafeMutablePointer<Bool>!) -> Void {
	return igShowDemoWindow(p_open)
}

@inlinable public func ImGuiShowFontSelector(_ label: String?) -> Void {
	label!.withCString { labelPtr in
		return igShowFontSelector(labelPtr)
	}
}

@inlinable public func ImGuiShowMetricsWindow(_ p_open: UnsafeMutablePointer<Bool>!) -> Void {
	return igShowMetricsWindow(p_open)
}

@inlinable public func ImGuiShowStyleEditor(_ ref: UnsafeMutablePointer<ImGuiStyle>!) -> Void {
	return igShowStyleEditor(ref)
}

@inlinable @discardableResult public func ImGuiShowStyleSelector(_ label: String?) -> Bool {
	label!.withCString { labelPtr in
		return igShowStyleSelector(labelPtr)
	}
}

@inlinable public func ImGuiShowUserGuide() -> Void {
	return igShowUserGuide()
}

@inlinable @discardableResult public func ImGuiSliderAngle(_ label: String?, _ v_rad: UnsafeMutablePointer<Float>!, _ v_degrees_min: Float, _ v_degrees_max: Float, _ format: String?) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igSliderAngle(labelPtr,v_rad,v_degrees_min,v_degrees_max,formatPtr)
		}
	}
}

@inlinable @discardableResult public func ImGuiSliderFloat(_ label: String?, _ v: UnsafeMutablePointer<Float>!, _ v_min: Float, _ v_max: Float, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igSliderFloat(labelPtr,v,v_min,v_max,formatPtr,power)
		}
	}
}

@inlinable @discardableResult public func ImGuiSliderFloat2(_ label: String?, _ v: inout SIMD2<Float>, _ v_min: Float, _ v_max: Float, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Float.self, capacity: 2) { vPtr in
				format!.withCString { formatPtr in
					return igSliderFloat2(labelPtr,vPtr,v_min,v_max,formatPtr,power)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiSliderFloat3(_ label: String?, _ v: inout SIMD3<Float>, _ v_min: Float, _ v_max: Float, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Float.self, capacity: 3) { vPtr in
				format!.withCString { formatPtr in
					return igSliderFloat3(labelPtr,vPtr,v_min,v_max,formatPtr,power)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiSliderFloat4(_ label: String?, _ v: inout SIMD4<Float>, _ v_min: Float, _ v_max: Float, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Float.self, capacity: 4) { vPtr in
				format!.withCString { formatPtr in
					return igSliderFloat4(labelPtr,vPtr,v_min,v_max,formatPtr,power)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiSliderInt(_ label: String?, _ v: UnsafeMutablePointer<Int32>!, _ v_min: Int32, _ v_max: Int32, _ format: String?) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igSliderInt(labelPtr,v,v_min,v_max,formatPtr)
		}
	}
}

@inlinable @discardableResult public func ImGuiSliderInt2(_ label: String?, _ v: inout SIMD2<Int32>, _ v_min: Int32, _ v_max: Int32, _ format: String?) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Int32.self, capacity: 2) { vPtr in
				format!.withCString { formatPtr in
					return igSliderInt2(labelPtr,vPtr,v_min,v_max,formatPtr)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiSliderInt3(_ label: String?, _ v: inout SIMD3<Int32>, _ v_min: Int32, _ v_max: Int32, _ format: String?) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Int32.self, capacity: 3) { vPtr in
				format!.withCString { formatPtr in
					return igSliderInt3(labelPtr,vPtr,v_min,v_max,formatPtr)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiSliderInt4(_ label: String?, _ v: inout SIMD4<Int32>, _ v_min: Int32, _ v_max: Int32, _ format: String?) -> Bool {
	label!.withCString { labelPtr in
		withUnsafeMutablePointer(to: &v) { vMutPtr in
			vMutPtr.withMemoryRebound(to: Int32.self, capacity: 4) { vPtr in
				format!.withCString { formatPtr in
					return igSliderInt4(labelPtr,vPtr,v_min,v_max,formatPtr)
				}
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiSliderScalar(_ label: String?, _ data_type: ImGuiDataType, _ p_data: UnsafeMutableRawPointer!, _ p_min: UnsafeRawPointer!, _ p_max: UnsafeRawPointer!, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igSliderScalar(labelPtr,data_type,p_data,p_min,p_max,formatPtr,power)
		}
	}
}

@inlinable @discardableResult public func ImGuiSliderScalarN(_ label: String?, _ data_type: ImGuiDataType, _ p_data: UnsafeMutableRawPointer!, _ components: Int32, _ p_min: UnsafeRawPointer!, _ p_max: UnsafeRawPointer!, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igSliderScalarN(labelPtr,data_type,p_data,components,p_min,p_max,formatPtr,power)
		}
	}
}

@inlinable @discardableResult public func ImGuiSmallButton(_ label: String?) -> Bool {
	label!.withCString { labelPtr in
		return igSmallButton(labelPtr)
	}
}

@inlinable public func ImGuiSpacing() -> Void {
	return igSpacing()
}

@inlinable public func ImGuiStorageBuildSortByKey(_ this: UnsafeMutablePointer<ImGuiStorage>!) -> Void {
	return ImGuiStorage_BuildSortByKey(this)
}

@inlinable public func ImGuiStorageClear(_ this: UnsafeMutablePointer<ImGuiStorage>!) -> Void {
	return ImGuiStorage_Clear(this)
}

@inlinable @discardableResult public func ImGuiStorageGetBool(_ this: UnsafeMutablePointer<ImGuiStorage>!, _ key: ImGuiID, _ default_val: Bool) -> Bool {
	return ImGuiStorage_GetBool(this,key,default_val)
}

@inlinable @discardableResult public func ImGuiStorageGetBoolRef(_ this: UnsafeMutablePointer<ImGuiStorage>!, _ key: ImGuiID, _ default_val: Bool) -> UnsafeMutablePointer<Bool>! {
	return ImGuiStorage_GetBoolRef(this,key,default_val)
}

@inlinable public func ImGuiStorageGetFloat(_ this: UnsafeMutablePointer<ImGuiStorage>!, _ key: ImGuiID, _ default_val: Float) -> Float {
	return ImGuiStorage_GetFloat(this,key,default_val)
}

@inlinable public func ImGuiStorageGetFloatRef(_ this: UnsafeMutablePointer<ImGuiStorage>!, _ key: ImGuiID, _ default_val: Float) -> UnsafeMutablePointer<Float>! {
	return ImGuiStorage_GetFloatRef(this,key,default_val)
}

@inlinable public func ImGuiStorageGetInt(_ this: UnsafeMutablePointer<ImGuiStorage>!, _ key: ImGuiID, _ default_val: Int32) -> Int32 {
	return ImGuiStorage_GetInt(this,key,default_val)
}

@inlinable public func ImGuiStorageGetIntRef(_ this: UnsafeMutablePointer<ImGuiStorage>!, _ key: ImGuiID, _ default_val: Int32) -> UnsafeMutablePointer<Int32>! {
	return ImGuiStorage_GetIntRef(this,key,default_val)
}

@inlinable public func ImGuiStorageGetVoidPtr(_ this: UnsafeMutablePointer<ImGuiStorage>!, _ key: ImGuiID) -> UnsafeMutableRawPointer! {
	return ImGuiStorage_GetVoidPtr(this,key)
}

@inlinable public func ImGuiStorageSetAllInt(_ this: UnsafeMutablePointer<ImGuiStorage>!, _ val: Int32) -> Void {
	return ImGuiStorage_SetAllInt(this,val)
}

@inlinable public func ImGuiStorageSetBool(_ this: UnsafeMutablePointer<ImGuiStorage>!, _ key: ImGuiID, _ val: Bool) -> Void {
	return ImGuiStorage_SetBool(this,key,val)
}

@inlinable public func ImGuiStorageSetFloat(_ this: UnsafeMutablePointer<ImGuiStorage>!, _ key: ImGuiID, _ val: Float) -> Void {
	return ImGuiStorage_SetFloat(this,key,val)
}

@inlinable public func ImGuiStorageSetInt(_ this: UnsafeMutablePointer<ImGuiStorage>!, _ key: ImGuiID, _ val: Int32) -> Void {
	return ImGuiStorage_SetInt(this,key,val)
}

@inlinable public func ImGuiStorageSetVoidPtr(_ this: UnsafeMutablePointer<ImGuiStorage>!, _ key: ImGuiID, _ val: UnsafeMutableRawPointer!) -> Void {
	return ImGuiStorage_SetVoidPtr(this,key,val)
}

@inlinable public func ImGuiStyleColorsClassic(_ dst: UnsafeMutablePointer<ImGuiStyle>!) -> Void {
	return igStyleColorsClassic(dst)
}

@inlinable public func ImGuiStyleColorsDark(_ dst: UnsafeMutablePointer<ImGuiStyle>!) -> Void {
	return igStyleColorsDark(dst)
}

@inlinable public func ImGuiStyleColorsLight(_ dst: UnsafeMutablePointer<ImGuiStyle>!) -> Void {
	return igStyleColorsLight(dst)
}

@inlinable public func ImGuiStyleScaleAllSizes(_ this: UnsafeMutablePointer<ImGuiStyle>!, _ scale_factor: Float) -> Void {
	return ImGuiStyle_ScaleAllSizes(this,scale_factor)
}

@inlinable public func ImGuiTextBufferAppend(_ this: UnsafeMutablePointer<ImGuiTextBuffer>!, _ str: String?, _ str_end: String?) -> Void {
	str!.withCString { strPtr in
		str_end!.withCString { str_endPtr in
			return ImGuiTextBuffer_append(this,strPtr,str_endPtr)
		}
	}
}

@inlinable public func ImGuiTextBufferAppendfv(_ this: UnsafeMutablePointer<ImGuiTextBuffer>!, _ fmt: String?, _ args: CVarArg...) -> Void {
	fmt!.withCString { fmtPtr in
		withVaList(args) { varArgsPtr in
			return ImGuiTextBuffer_appendfv(this,fmtPtr,varArgsPtr)
		}
	}
}

@inlinable public func ImGuiTextBufferBegin(_ this: UnsafeMutablePointer<ImGuiTextBuffer>!) -> String? {
	return String(cString: ImGuiTextBuffer_begin(this))
}

@inlinable public func ImGuiTextBufferCStr(_ this: UnsafeMutablePointer<ImGuiTextBuffer>!) -> String? {
	return String(cString: ImGuiTextBuffer_c_str(this))
}

@inlinable public func ImGuiTextBufferClear(_ this: UnsafeMutablePointer<ImGuiTextBuffer>!) -> Void {
	return ImGuiTextBuffer_clear(this)
}

@inlinable @discardableResult public func ImGuiTextBufferEmpty(_ this: UnsafeMutablePointer<ImGuiTextBuffer>!) -> Bool {
	return ImGuiTextBuffer_empty(this)
}

@inlinable public func ImGuiTextBufferEnd(_ this: UnsafeMutablePointer<ImGuiTextBuffer>!) -> String? {
	return String(cString: ImGuiTextBuffer_end(this))
}

@inlinable public func ImGuiTextBufferReserve(_ this: UnsafeMutablePointer<ImGuiTextBuffer>!, _ capacity: Int32) -> Void {
	return ImGuiTextBuffer_reserve(this,capacity)
}

@inlinable public func ImGuiTextBufferSize(_ this: UnsafeMutablePointer<ImGuiTextBuffer>!) -> Int32 {
	return ImGuiTextBuffer_size(this)
}

@inlinable public func ImGuiTextColoredV(_ col: ImVec4, _ fmt: String?, _ args: CVarArg...) -> Void {
	fmt!.withCString { fmtPtr in
		withVaList(args) { varArgsPtr in
			return igTextColoredV(col,fmtPtr,varArgsPtr)
		}
	}
}

@inlinable public func ImGuiTextDisabledV(_ fmt: String?, _ args: CVarArg...) -> Void {
	fmt!.withCString { fmtPtr in
		withVaList(args) { varArgsPtr in
			return igTextDisabledV(fmtPtr,varArgsPtr)
		}
	}
}

@inlinable public func ImGuiTextFilterBuild(_ this: UnsafeMutablePointer<ImGuiTextFilter>!) -> Void {
	return ImGuiTextFilter_Build(this)
}

@inlinable public func ImGuiTextFilterClear(_ this: UnsafeMutablePointer<ImGuiTextFilter>!) -> Void {
	return ImGuiTextFilter_Clear(this)
}

@inlinable @discardableResult public func ImGuiTextFilterDraw(_ this: UnsafeMutablePointer<ImGuiTextFilter>!, _ label: String?, _ width: Float) -> Bool {
	label!.withCString { labelPtr in
		return ImGuiTextFilter_Draw(this,labelPtr,width)
	}
}

@inlinable @discardableResult public func ImGuiTextFilterIsActive(_ this: UnsafeMutablePointer<ImGuiTextFilter>!) -> Bool {
	return ImGuiTextFilter_IsActive(this)
}

@inlinable @discardableResult public func ImGuiTextFilterPassFilter(_ this: UnsafeMutablePointer<ImGuiTextFilter>!, _ text: String?, _ text_end: String?) -> Bool {
	text!.withCString { textPtr in
		text_end!.withCString { text_endPtr in
			return ImGuiTextFilter_PassFilter(this,textPtr,text_endPtr)
		}
	}
}

@inlinable @discardableResult public func ImGuiTextRangeEmpty(_ this: UnsafeMutablePointer<ImGuiTextRange>!) -> Bool {
	return ImGuiTextRange_empty(this)
}

@inlinable public func ImGuiTextRangeSplit(_ this: UnsafeMutablePointer<ImGuiTextRange>!, _ separator: CChar, _ out: UnsafeMutablePointer<ImVector_ImGuiTextRange>!) -> Void {
	return ImGuiTextRange_split(this,separator,out)
}

@inlinable public func ImGuiTextUnformatted(_ text: String?, _ text_end: String?) -> Void {
	text!.withCString { textPtr in
		text_end!.withCString { text_endPtr in
			return igTextUnformatted(textPtr,text_endPtr)
		}
	}
}

@inlinable public func ImGuiTextV(_ fmt: String?, _ args: CVarArg...) -> Void {
	fmt!.withCString { fmtPtr in
		withVaList(args) { varArgsPtr in
			return igTextV(fmtPtr,varArgsPtr)
		}
	}
}

@inlinable public func ImGuiTextWrappedV(_ fmt: String?, _ args: CVarArg...) -> Void {
	fmt!.withCString { fmtPtr in
		withVaList(args) { varArgsPtr in
			return igTextWrappedV(fmtPtr,varArgsPtr)
		}
	}
}

@inlinable @discardableResult public func ImGuiTreeNodeExStr(_ label: String?, _ flags: ImGuiTreeNodeFlags) -> Bool {
	label!.withCString { labelPtr in
		return igTreeNodeExStr(labelPtr,flags)
	}
}

@inlinable @discardableResult public func ImGuiTreeNodeExVPtr(_ ptr_id: UnsafeRawPointer!, _ flags: ImGuiTreeNodeFlags, _ fmt: String?, _ args: CVarArg...) -> Bool {
	fmt!.withCString { fmtPtr in
		withVaList(args) { varArgsPtr in
			return igTreeNodeExVPtr(ptr_id,flags,fmtPtr,varArgsPtr)
		}
	}
}

@inlinable @discardableResult public func ImGuiTreeNodeExVStr(_ str_id: String?, _ flags: ImGuiTreeNodeFlags, _ fmt: String?, _ args: CVarArg...) -> Bool {
	str_id!.withCString { str_idPtr in
		fmt!.withCString { fmtPtr in
			withVaList(args) { varArgsPtr in
				return igTreeNodeExVStr(str_idPtr,flags,fmtPtr,varArgsPtr)
			}
		}
	}
}

@inlinable @discardableResult public func ImGuiTreeNodeStr(_ label: String?) -> Bool {
	label!.withCString { labelPtr in
		return igTreeNodeStr(labelPtr)
	}
}

@inlinable @discardableResult public func ImGuiTreeNodeVPtr(_ ptr_id: UnsafeRawPointer!, _ fmt: String?, _ args: CVarArg...) -> Bool {
	fmt!.withCString { fmtPtr in
		withVaList(args) { varArgsPtr in
			return igTreeNodeVPtr(ptr_id,fmtPtr,varArgsPtr)
		}
	}
}

@inlinable @discardableResult public func ImGuiTreeNodeVStr(_ str_id: String?, _ fmt: String?, _ args: CVarArg...) -> Bool {
	str_id!.withCString { str_idPtr in
		fmt!.withCString { fmtPtr in
			withVaList(args) { varArgsPtr in
				return igTreeNodeVStr(str_idPtr,fmtPtr,varArgsPtr)
			}
		}
	}
}

@inlinable public func ImGuiTreePop() -> Void {
	return igTreePop()
}

@inlinable public func ImGuiTreePushPtr(_ ptr_id: UnsafeRawPointer!) -> Void {
	return igTreePushPtr(ptr_id)
}

@inlinable public func ImGuiTreePushStr(_ str_id: String?) -> Void {
	str_id!.withCString { str_idPtr in
		return igTreePushStr(str_idPtr)
	}
}

@inlinable public func ImGuiUnindent(_ indent_w: Float) -> Void {
	return igUnindent(indent_w)
}

@inlinable @discardableResult public func ImGuiVSliderFloat(_ label: String?, _ size: ImVec2, _ v: UnsafeMutablePointer<Float>!, _ v_min: Float, _ v_max: Float, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igVSliderFloat(labelPtr,size,v,v_min,v_max,formatPtr,power)
		}
	}
}

@inlinable @discardableResult public func ImGuiVSliderInt(_ label: String?, _ size: ImVec2, _ v: UnsafeMutablePointer<Int32>!, _ v_min: Int32, _ v_max: Int32, _ format: String?) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igVSliderInt(labelPtr,size,v,v_min,v_max,formatPtr)
		}
	}
}

@inlinable @discardableResult public func ImGuiVSliderScalar(_ label: String?, _ size: ImVec2, _ data_type: ImGuiDataType, _ p_data: UnsafeMutableRawPointer!, _ p_min: UnsafeRawPointer!, _ p_max: UnsafeRawPointer!, _ format: String?, _ power: Float) -> Bool {
	label!.withCString { labelPtr in
		format!.withCString { formatPtr in
			return igVSliderScalar(labelPtr,size,data_type,p_data,p_min,p_max,formatPtr,power)
		}
	}
}

@inlinable public func ImGuiValueBool(_ `prefix`: String?, _ b: Bool) -> Void {
	`prefix`!.withCString { prefixPtr in
		return igValueBool(prefixPtr,b)
	}
}

@inlinable public func ImGuiValueFloat(_ `prefix`: String?, _ v: Float, _ float_format: String?) -> Void {
	`prefix`!.withCString { prefixPtr in
		float_format!.withCString { float_formatPtr in
			return igValueFloat(prefixPtr,v,float_formatPtr)
		}
	}
}

@inlinable public func ImGuiValueInt(_ `prefix`: String?, _ v: Int32) -> Void {
	`prefix`!.withCString { prefixPtr in
		return igValueInt(prefixPtr,v)
	}
}

@inlinable public func ImGuiValueUint(_ `prefix`: String?, _ v: UInt32) -> Void {
	`prefix`!.withCString { prefixPtr in
		return igValueUint(prefixPtr,v)
	}
}

@inlinable public func ImVectorResizeNil(_ this: UnsafeMutablePointer<ImVector>!, _ new_size: Int32) -> Void {
	return ImVector_resizeNil(this,new_size)
}

@inlinable public func ImVectorShrink(_ this: UnsafeMutablePointer<ImVector>!, _ new_size: Int32) -> Void {
	return ImVector_shrink(this,new_size)
}

