//
//  main.swift
//
//
//  Created by Christian Treffs on 24.10.19.
//

import struct Foundation.URL
import struct Foundation.Data

public struct ConversionError: Swift.Error {
    public let localizedDescription: String
}

public func getDirectory(ofFile filePath: String = #file) -> String {
    guard let lastSlashIdx = filePath.lastIndex(of: "/") else {
        return filePath
    }
    var dirPath = filePath
    dirPath.removeSubrange(lastSlashIdx..<filePath.endIndex)
    return dirPath
}

// Input: <SRC_ROOT>/3rdparty/cimgui/generator/output/definitions.json
public let kInputFile: String
// Output <SRC_ROOT>/Sources/ImGui/ImGui+Definitions.swift
public let kOutputFile: String

if CommandLine.arguments.count == 3 {
    kInputFile = CommandLine.arguments[1]
    kOutputFile = CommandLine.arguments[2]
} else {
    kInputFile = getDirectory() + "/../../3rdparty/cimgui/generator/output/definitions.json"
    kOutputFile = getDirectory() + "/../ImGui/ImGui+Definitions.swift"
}

public let kHeader = """
// -- THIS FILE IS AUTOGENERATED - DO NOT EDIT!!! ---

import CImGui

// swiftlint:disable identifier_name

// Undeclared type definitions
\(Exceptions.undeclardTypes.values
.map { "public typealias \($0.name) = \($0.typealiasType)" }
.sorted()
.joined(separator: "\n"))

"""

public let kFooter = """
"""

try convert(filePath: kInputFile, validOnly: true) { body in
    let out: String = [kHeader, body, kFooter].joined(separator: "\n\n")

    guard let data: Data = out.data(using: .utf8) else {
        throw ConversionError(localizedDescription: "Could not generate data from output string \(out)")
    }

    let outURL = URL(fileURLWithPath: kOutputFile)

    try data.write(to: outURL)
}
