name: Linux

on:
  push:
    branches: [ master, docking ]
  pull_request:
    branches: [ master, docking ]
  workflow_dispatch:

jobs:
  linux-test-build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["latest"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: make test
      - name: Build Release
        run: make build-release
