name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  macos-test-build-release-xcode:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ["13.4.1", "14.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Test
        run: make test
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      
      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v3.2.1
        with:
          name: test-artifacts-${{ matrix.xcode }}-${{ github.run_id }}
          path: |
            .build/**/*.json
            .build/**/*.xctest
      
      - name: Build Release
        run: make build-release
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      
      - name: Upload build artifacts
        if: failure()
        uses: actions/upload-artifact@v3.2.1
        with:
          name: build-artifacts-${{ matrix.xcode }}-${{ github.run_id }}
          path: |
            *.lcov
            .build/*.yaml
            .build/**/*.a
            .build/**/*.so
            .build/**/*.dylib
            .build/**/*.dSYM 
            .build/**/*.json
