name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows-test-build-release:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.7-release
          tag: 5.7-RELEASE

      - name: Checkout
        uses: actions/checkout@v3.5.2
    
      - name: Test
        run: swift test -v --enable-test-discovery

      - name: Build Release
        run: swift build -c release